### ISSUE TITLE
Package abandoned

### ISSUE THREAD

**Issue by asivaneswaran** [eminiarts/nova-tabs#104]
Hey, is the package abandoned? Or will it work with Nova 3.9.0?

**Comment by RVxLab** [comment]
@asivaneswaran It works with Nova 3.9.0 on Laravel 8, PHP 7.4.

**Comment by RVxLab** [comment]
The original maintainer of this package unfortunately did not have the time anymore to actively maintain this.

I stepped in to help maintain this. Consider it not abandoned. :)

**Comment by asivaneswaran** [comment]
Great news. Thanks!
