### ISSUE TITLE
TabsOnEdit trait does not work in Nova 3.12.0

### ISSUE THREAD

**Issue by vbezruchkin** [eminiarts/nova-tabs#109]
Hi,

Tabs are not displayed on Edit page. When you get rid of the trait, they are displayed fine. 
Tabs are available on Insert / View page.

PHP Version  |  7.4.6
Laravel Version | 8.9.0
Nova Version | 3.12.0

Thanks in advance.

**Comment by ziming** [comment]
Can confirm this. This is a very popular package for nova. Hope @crynobone can help on this.

**Comment by LorenzoSapora** [comment]
Confirmed, and it's a silent error, too. Had to do some manual testing to find out which package caused the issue. I would assume this is an issue with https://github.com/laravel/nova/pull/1000/files, but unsure how or why it broke tabs.

**Comment by LorenzoSapora** [comment]
@RVxLab seems to be maintaining this package from other PRs here. I'll see if I can spend some time digging into the issue

**Comment by LorenzoSapora** [comment]
Nova `v3.12.1` this has this issue.

**Comment by randomparanoia** [comment]
Same here. I was not able to dig the problem but since I am using a trait from other package, some resources are working?! The trait is from [](https://github.com/dcasia/conditional-container)https://github.com/dcasia/conditional-container

**Comment by LorenzoSapora** [comment]
Very interesting.. @randomparanoia is correct, if you use that package/trait, it works again. It must be some class that it extends that the update breaks. I'll look into this after work.

**Comment by vbezruchkin** [comment]
thanks in advance @LorenzoSapora

**Comment by Dontorpedo** [comment]
@randomparanoia 

lol, strange.. same for me..

my edit view was not visible until i added this package and trait..

i am on laravel 8, nova 3.12.1

**Comment by RVxLab** [comment]
@LorenzoSapora If you do manage to take a look, please do tell me what you find and I'll try to implement a fix for this.

**Comment by Dontorpedo** [comment]
seems like it has something to do with this [PR](https://github.com/laravel/nova/pull/1000/files)

**Comment by RVxLab** [comment]
Good to know, I'll take a look at this.

**Comment by RVxLab** [comment]
@Dontorpedo Thanks again for that reference, I was able to find the issue and fix it.

See #111 

I'm going to contact @bajramemini to tag 1.2.3 and get this out there.

**Comment by stefvanesch** [comment]
@Dontorpedo Thanks for fixing this so quickly :) @bajramemini any estimate on when this will be released?

**Comment by RVxLab** [comment]
@stefvanesch Until the package is on Packagist you could refer to `dev-master` for now. Look out for version `1.2.3`.

**Comment by vbezruchkin** [comment]
Thanks much! It's working now. Just updated to the latest dev version.

**Comment by RVxLab** [comment]
I'm happy to hear it's working for you. I'll update this issue when the next tag is available.
