### ISSUE TITLE
Nearly a year since last release, but has fixes in master

### ISSUE THREAD

**Issue by LorenzoSapora** [eminiarts/nova-tabs#110]
I currently have composer to pull `dev-master`, so the issue isn't too important for me, but there have been some fixes waiting in master that would be very useful to users who still have this package pegged to `v1.2.2`.

**Comment by RVxLab** [comment]
I'm very aware and I very much agree with you. I'd like to add a couple more fixes into master before pushing a new release. I'm hoping to get to this over the weekend.

**Comment by RVxLab** [comment]
1.2.3 was just tagged.
