### ISSUE TITLE
[Feature-Request] Allowed nested tabs

### ISSUE THREAD

**Issue by ThaDaVos** [eminiarts/nova-tabs#115]
In a special case I want to add a nested tabs list but I get an error: 
![image](https://user-images.githubusercontent.com/5251028/96447444-330af700-1212-11eb-9c5f-bfdbeb69bdc0.png)

Is there a way around this to allow a nested tabs?

**Comment by ThaDaVos** [comment]
Never mind the error - that was something else - but when adding `Tabs` as child of `Tabs` it won't show tabs at all...

**Comment by RVxLab** [comment]
Is there any particular use you're after for this? To me it seems like putting tabs within tabs is a great way to get lost in your data.

**Comment by bajramemini** [comment]
It wasn't intended to work like this. I have to agree with @RVxLab that you could easily get lost in your data if you have multiple tabs within multiple tabs.
