### ISSUE TITLE
When using nova-tabs, detail page is missing :title.

### ISSUE THREAD

**Issue by preliot** [eminiarts/nova-tabs#118]
Laravel Nova now uses ":resource Details: :title" to show a detail page title. But on pages with nova-tabs, i can only see ":resource Details". Can this be a nova tabs issue?

**Comment by RVxLab** [comment]
Hey Preliot, I'll look into this.

**Comment by RVxLab** [comment]
I had a look but I can't really find what you mean. Could you send a screenshot?

**Comment by preliot** [comment]
See you've found it and created a fix. Nice!

**Comment by RVxLab** [comment]
As I wrote my previous comment I found out what you meant. I contacted the repo owner to tag this for 1.3, until then you can use the master branch or reference that commit. :)
