### ISSUE TITLE
Switching tabs causes a full page refresh

### ISSUE THREAD

**Issue by jkudish** [eminiarts/nova-tabs#120]
Hey there,

I'm using the latest version of Nova and the latest version (1.3.0) of this package and switching tabs is now causing full page refreshes instead of a partial reload of the tab like it's supposed to. Here's a video illustrating the issue:

https://dsc.cloud/sparkdev/CleanShot-2020-11-09-at-10.36.32.mp4

I tried:

* Composer update
* Clearing browser cache
* `php artisan nova:publish`

But issue persists.

I've downgraded the package back to 1.2.3 and the issue is resolved, so I'm fairly confident the issue appeared in the latest version of this package.

Thanks!

**Comment by RVxLab** [comment]
I have a hunch this happens during the URL update when you switch tabs since it edits the query string.

I'll need to do a bit of research.

**Comment by RVxLab** [comment]
I'm unable to reproduce this in Chrome and Firefox using 1.3.0 and Nova 3.15 in the way you're stating. However I do notice that nova shows a loading bar in the top of the window which may indicate a reload. 

I'm gonna need some more info regarding your setup on this.

**Comment by jkudish** [comment]
Hey @RVxLab 

Thanks for getting back to me. Sorry I didn't see your reply right away.

I just tried again with 1.3.1 and the issue persists. In hindsight, and after looking at the network tab in the chrome dev tools, I do see that it does not do a full page refresh. However, yes it shows the loading bar, and temporarily hides all of the components pages, and reloads every component on the page, re-doing all of the XHR requests that it needs to pull in all the data on the page; basically it looks like a full page refresh.

What additional info can I provide?

**Comment by RVxLab** [comment]
A generalized list of your setup would be helpful. I'm trying to find out whether this has something to do with the way Nova uses the Router. As Nova Tabs updates the query string, I wonder in what way either Nova, or maybe some other package you use, reacts to it.

**Comment by jkudish** [comment]
I tried this with a clean install of Laravel & Nova and you're right that there's no issue there. I spent a little bit of time trying to isolate the issue with some of the packages and custom code we have in use, but couldn't quite pin-point the issue. I'll leave this be for now as I don't think there's a generalized issue in your package, but I might come back if I do end up finding the culprit and have a solution to suggest.

Sorry for the trouble, thanks!

**Comment by RVxLab** [comment]
If you do find what's wrong I'd love to know.

Thanks for opening this issue, feel free to reopen this when needed.

**Comment by MB116** [comment]
Hello everyone!
I have the same problem, have you found a solution?

**Comment by renzo-s** [comment]
Use your Vue devtools routing tab to debug this and take notice of any differences in params and types!

I had the same issue, and I noticed the `resourceId` I used to navigate to the main page with tabs was an `int`. But when the tabs navigated between each other, the `resourceId` was a `string`. So I updated my router link and the issue was gone 🎉.

For example:

```html
<router-link
    class="block no-underline text-90 hover:bg-30 p-3"
    :to="{
        name: 'edit',
        params: {
            resourceName: '{{ call_user_func('\App\Resources\Profile::uriKey') }}',
            // resourceId: {{ $user->id }},  // 👈 This is an int, where the tabs expect a string
            resourceId: '{{ $user->id }}',  // 👈 A few quotes fixed the problem
        },
    }"
>
    {{ __('Profile settings') }}
</router-link>
```

**Comment by RVxLab** [comment]
@renzo-s Very interesting observation. I'm now wondering if this happens because of the query string update that happens when clicking on a tab. I'll try to investigate this over the weekend.

**Comment by RVxLab** [comment]
I had a look and to find out I had to do look in the Nova sources and this looks to happen in Nova's subscriptions to the Vue Router. So far it looks like that short of taking this feature out and turning it into something from localStorage, this isn't something that seems to be fixable.
