### ISSUE TITLE
The search bar not position correctly Nova 3.15.0

### ISSUE THREAD

**Issue by asivaneswaran** [eminiarts/nova-tabs#121]
After the update to Nova 3.15.0, I have an issue with tabs that have a search bar:
<img width="680" alt="Screen Shot 2020-11-16 at 20 35 41" src="https://user-images.githubusercontent.com/2759350/99329077-76757700-284b-11eb-951a-1c4b1f44ff39.png">

**Comment by RVxLab** [comment]
I'll take a look this weekend, may be a margin issue.
