### ISSUE TITLE
Problem with sidebar button

### ISSUE THREAD

**Issue by DavidPuzder** [eminiarts/nova-tabs#123]
On sidebar is not clickable Settings button with laravel nova v3.15.0
![Screenshot_1](https://user-images.githubusercontent.com/36508590/99582050-d867e500-29e1-11eb-9228-7d223efeb5b4.png)

**Comment by RVxLab** [comment]
Could you provide a way so I can accurately reproduce this?

**Comment by RVxLab** [comment]
Closed due to inactivity.
