### ISSUE TITLE
1.3.0 Removes query arguments from url

### ISSUE THREAD

**Issue by preliot** [eminiarts/nova-tabs#124]
Version 1.3.0 adds ?tab=<name-of-tab> to the url. The issue is it replaces any existing query string, which breaks any code that relies on that query string. Would be better if something like this is done:

1. Retrieve query string, put in array
2. Replace existing tab / add new tab=<name-of-tab>
3. Implode array to url

**Comment by RVxLab** [comment]
Crap, I didn't think of that when merging the PR for this. Thanks for your report, I'll take a look over the weekend.

**Comment by preliot** [comment]
@RVxLab No worries! And thanks for taking some time for this in the weekend, i appreciate it!

**Comment by RVxLab** [comment]
@preliot Your issue has been fixed, please update to 1.3.1.

**Comment by preliot** [comment]
Can confirm it's fixed, thanks!
