### ISSUE TITLE
Error: Unexpected end of input. tabs:1 - help wanted

### ISSUE THREAD

**Issue by mikhi** [eminiarts/nova-tabs#126]
Hi,

i made an update from laravel 6 to laravel 7, and from nova 2.x to 3.15.0

On create and edit forms, no inputs are displayed, and in console i get the following error:

*Uncaught SyntaxError: Unexpected end of input.  tabs:1*

![image](https://user-images.githubusercontent.com/1406293/100258001-3602b100-2f4f-11eb-8ac3-0b8ac478ccff.png)

![image](https://user-images.githubusercontent.com/1406293/100257424-904f4200-2f4e-11eb-845d-12799f97f679.png)

Any idea?

**Comment by RVxLab** [comment]
Doesn't seem like an issue with nova-tabs directly. I'm gonna need way more info than this. 

Which version of the package are you using?

If using the latest (1.3.1 as of now), did you follow the Nova upgrade guide?

If so, please compile nova-tabs' JS for development:

- `cd vendor/eminiarts/nova-tabs`
- `yarn` (or `npm i`, `yarn` is preferred)
- `yarn dev`

Optionally, compile Nova's assets for development as per https://nova.laravel.com/docs/3.0/customization/frontend.html#vue-devtools

**Comment by mikhi** [comment]
Hi @RVxLab 
i use 
"laravel/framework": "^7.0",
"laravel/nova": "*", - the version is 3.15.0
"eminiarts/nova-tabs": "^1.3"

i also use
Valet with
PHP 7.4.12
MYSQL  Ver 8.0.22 for osx10.16 on x86_64 (Homebrew)

I followed your advice to compile nova-tabs and also to recompile nova assets, but the result is the same.

**Comment by RVxLab** [comment]
Naturally this will not be a magic fix, this should however give you some more debug output. Can you post that?

**Comment by mikhi** [comment]
Your right, is not a magic fix. 
However, I isolated the problem. It seems that the trait TabsOnEdit breaks the form.

If i use the TabsOnEdit trait the error below is displayed in console:
![image](https://user-images.githubusercontent.com/1406293/100354954-9bab7780-2ff9-11eb-9e23-7fc03009ce16.png)

**Comment by RVxLab** [comment]
That's very odd, [this component is most definitely registered.](https://github.com/eminiarts/nova-tabs/blob/master/resources/js/field.js#L3)

Is the script being loaded correctly? Please ensure that the service provider is loaded and that the script is being loaded correctly.

**Comment by mikhi** [comment]
Sorry for being dumb, but i don't know how to check if the scripts are loaded correctly.  Also the service provider is not automatically loaded by Laravel?
I have downgraded nova from 3.15.0 to 3.8.4, but the result is the same.

If i use tabs on Details or in form using TabsOnEdit trait the screen in blank.

Ex: 
**Details screen**
![image](https://user-images.githubusercontent.com/1406293/100372470-ef29bf80-3011-11eb-981f-bc2c82aa49a8.png)

**Create / Edit screen using the trait**
![image](https://user-images.githubusercontent.com/1406293/100372590-25ffd580-3012-11eb-8e3d-be37ba61f053.png)

**Create / Edit screen without the trait**
![image](https://user-images.githubusercontent.com/1406293/100372652-3ca62c80-3012-11eb-9ef7-b0698b42c9d2.png)

The console looks like this
![image](https://user-images.githubusercontent.com/1406293/100372742-63646300-3012-11eb-9d17-d10f6c8a2c1b.png)

**Composer.json**
![image](https://user-images.githubusercontent.com/1406293/100373027-c7872700-3012-11eb-86ae-a17f1268556a.png)
![image](https://user-images.githubusercontent.com/1406293/100373187-0f0db300-3013-11eb-8c95-b37cf552ec98.png)

** app.php  > providers array **

![image](https://user-images.githubusercontent.com/1406293/100373591-ae32aa80-3013-11eb-9f89-90f28d684236.png)

**Comment by RVxLab** [comment]
So far it looks like the script isn't loaded in. 

Can you see the script?

```js
document.querySelectorAll('script');
```

**Comment by mikhi** [comment]
Pfff... Thank you for opening my eyes. Somehow that was the problem...
In details: I use  "renatomarinho / laravel-page-speed" package that removes unnecessary whitespace in HTML. This package is used in frontend, but it also affects the backend...

The results is something like:

![image](https://user-images.githubusercontent.com/1406293/100385404-28225e00-302b-11eb-9401-ea50e536728b.png)

i suppose comments like 
```
//comments
```
 are used somewhere in code/other packages and that was the cause.

Thank you for your help and patience!

**Comment by RVxLab** [comment]
I'm glad to know you found the issue. It's good to keep a note that `renatomarinho/laravel-page-speed` can cause this.

You're very welcome! If there's anything else, feel free to let me know.
