### ISSUE TITLE
How to customize a tab name in a URL?

### ISSUE THREAD

**Issue by martio** [eminiarts/nova-tabs#127]
How to customize a tab name in a URL?

Instead of: "http://localhost/admin/resources/users/1?tab=Aktywno%C5%9Bci" there must be: "http://localhost/admin/resources/users/1?tab=activities"

```
HasMany::make(__('nova.resources.tabs.user.panels.activities'), 'activities', Activity::class),
```

**Comment by RVxLab** [comment]
Currently this is not possible. It's dictated by the tab name.

This is a good idea to have though. If you want to create a PR for this feel free to do so. Otherwise I'll take a look next week.

**Comment by keironwaites** [comment]
Came here to vote for this. Please see the attached photo for a real world use-case. I include a record count in my tab name which will change over time and cause the tab deep linking to become unreliable.

<img width="868" alt="Screenshot 2020-12-03 at 13 59 53" src="https://user-images.githubusercontent.com/23054272/101027611-221f0680-3570-11eb-8edf-901003b9e181.png">

**Comment by RVxLab** [comment]
I definitely agree that this is a very good improvement. As I'm gonna be busy this weekend, I will take a look next week. However, for backwards compatibility reasons this would not be enabled by default.

This is how I would likely implement this:

- Add a slug method to the `Tab` which accepts a nullable string.
- The `$slug` property would default to the sluggified name.
- Then it'll be passed to the Vue component which will pass it to the router.

I'd like to hear what you think.

**Comment by keironwaites** [comment]
Sound plan.

**Comment by keironwaites** [comment]
I am working with tabs now to validate actions within authorizedToCreate(). It would be imperative for me that $request->tab contained the $slug value.

This is probably already the planned approach but I wanted to make a point of it just in case.

Thank you.

**Comment by RVxLab** [comment]
Alright so I had a look. In the current state of the package this isn't possible. However with the ideas mentioned in #129 this would be made possible. I'm going to need to write this one out and plan this correctly as this would be a MASSIVE change.

I'll keep this issue open for the time being and refer to it when I'm ready to post an issue to address #129.

**Comment by RVxLab** [comment]
This has been implemented with the new `Tab` object and is available in master. I'm not ready to tag this yet as I'm still wanting to do some updates and fixes. Until 1.4.0 you can use `dev-master`.
