### ISSUE TITLE
Implementation for Tab object

### ISSUE THREAD

**Issue by RVxLab** [eminiarts/nova-tabs#130]
Branch: https://github.com/eminiarts/nova-tabs/tree/feature/tabs-object

Implementation for the proposal in #129 

To implement a `Tab` object I propose the following interface:

```php
interface TabContract
{
    // Through the Makeable trait
    public static function make(string $title, array $fields, array $options = []): self;

    public function name(string $name): self;

    public function showIf(bool | callable $condition): self;

    public function showUnless(bool | callable $condition): self;

    public function titleAsHtml(bool $titleAsHtml = true): self;

    public function beforeIcon(string $iconAsHtml): self;

    public function afterIcon(string $iconAsHtml): self;

    public function tabClass(string | array $classes): self;

    public function bodyClass(string | array $classes): self;
}
```
## Macroable

The `Tab` class would implement the `Illuminate\Support\Traits\Macroable` trait to implement macros.

However, if deeper adjustments are required, it would be better to extend the `Tab` class or make a custom implementation based on the `TabContract` interface.

## Backwards compatibility

The current way to define tabs would remain a valid way to define them, but seeing that the `Tab` class would provide more flexibility, the array method could be considered obsolete or even deprecated.

If chosen for deprecation, I vote to remove the feature in a 2.0 release.

## Implementation plan

The plan to implement this feature would be as follows:

1. Create tests to ensure the current functionality does not break (PHPUnit with possibly Pest).
2. Implement the newly planned features and add tests for them on the backend
3. Implement these changes in the frontend

Additionally, as this feature would add quite a few new things to the frontend, this would be a good time to do some clean up these. 

1. Split components for better re-usability
2. Add ESLint and/or Prettier for code quality
3. Ideally, use Jest to test these components

Finally, I'd like to start making use of GitHub Actions for some automation.

**Comment by bernhardh** [comment]
As requested in #129 I would also add a `tabClass` and a `bodyClass`, so that you can give each tab and tab-body an individual style (for example background color) if needed).

**Comment by RVxLab** [comment]
@bernhardh Those requests have been added to the interface above.

**Comment by RVxLab** [comment]
The new `Tab` class has been implemented into the `Tabs` class and can now be used.

For those willing to try it out, you can use the feature/tabs-object branch. Mind you that at this time only the following fields are functional:

- `showIf`
- `showUnless`
- `name`

I will add the new properties to the Vue side soon.

**Comment by RVxLab** [comment]
This is now available in master.
