### ISSUE TITLE
Need help with showTitle()

### ISSUE THREAD

**Issue by terry-greenlaw** [eminiarts/nova-tabs#132]
I'm trying to display the default Nova title and toolbar on the detail page, with my non-relationship fields in one tab, and a tab for each relationship.
I haven't been able to figure out the right combination of showToolbar(), showTitle(), and panel usage to get the default Nova title to show.
Does anyone have an example they could share?

**Comment by RVxLab** [comment]
I’m not exactly sure what your question is. Can you please elaborate?

**Comment by C14r** [comment]
I think he is trying this:

One tabs field on the ressource display (no normal field above the tabs).

- First Tab: one Panel with different fields
- Second Tab: Relation
- Third Tab: Relation
- ...

And then he wants to show the "normal" title and buttons on the page. If you use showToolbar() the default title of the page is not showing, instead the provider title is shown.

**Comment by terry-greenlaw** [comment]
I found the solution in a closed issue. Passing $this->title() to make() does what I was looking for. Closing as resolved.
Tabs::make($this->title(), [...
