### ISSUE TITLE
Cannot create resource from relationship tab (issue occurring again since new update)

### ISSUE THREAD

**Issue by navidnadali** [eminiarts/nova-tabs#136]
Hi @bajramemini , Great package and thank you

The first issue ever created ( #1 ) is now reoccurring and can be reproduced in exactly the same way since one of the new updates (or maybe since a nova update?).. 

Thanks
Navid

**Comment by RVxLab** [comment]
Hi Navid, could you provide me a stack trace, as well as package, Nova and PHP version?

Thanks

**Comment by RVxLab** [comment]
Due to inactivity I'm closing this issue. If this issue still occurs please open a new issue with more information.
