### ISSUE TITLE
Relevent Tab is not getting highlighted after modifing  / attaching the data 

### ISSUE THREAD

**Issue by Piusha** [eminiarts/nova-tabs#137]
I have 2 tabs
1st tab is for genral information 2nd tabs is for attaching countries (BelongsToMany::make('Countries'))

After I attached countries it isalway navigating to the Genral information tab. Not for the country tab. I want it to be in Country tab as I modified data from Country tab. 
Is there any posible way to do that?

Nova version : 3.20.0
eminiarts/nova-tabs version : 1.3.1

**Comment by RVxLab** [comment]
Does the `?tab` querystring disappear after redirect?

**Comment by thijskuilman** [comment]
This is something I've also encountered. I solved it by overwriting the `redirectAfterCreate()` and `redirectAfterUpdate()` in `app/Nova/Resource.php`. I've added a bit of code that appends the ?tab query string if you're coming from a relationship tab.

Here's the code:


```
 /**
 * @param NovaRequest $request
 * @param NovaResource $resource
 * @return string
 */
public static function redirectAfterCreate(NovaRequest $request, $resource)
{
    if ($request->viaResource) {
        $previousUrl = "/resources/{$request->viaResource}/{$request->viaResourceId}";
        if ($request->viaRelationship) {
            $previousUrl .= "?tab=" . strtolower(__($request->viaRelationship));
        }
        return $previousUrl;
    }

    return parent::redirectAfterCreate($request, $resource);
}

/**
 * @param NovaRequest $request
 * @param NovaResource $resource
 * @return string
 */
public static function redirectAfterUpdate(NovaRequest $request, $resource)
{
    if ($request->viaResource) {
        $previousUrl = "/resources/{$request->viaResource}/{$request->viaResourceId}";
        if ($request->viaRelationship) {
            $previousUrl .= "?tab=" . strtolower(__($request->viaRelationship));
        }
        return $previousUrl;
    }
    return parent::redirectAfterUpdate($request, $resource);
}
```

**Comment by RVxLab** [comment]
Due to inactivity I'm closing this issue. If this issue still occurs please open a new issue.
