### ISSUE TITLE
Separate fields outside and inside tabs on update view

### ISSUE THREAD

**Issue by simonfunk** [eminiarts/nova-tabs#14]
Hi, me again :)

Thanks for the amazing work on https://github.com/eminiarts/nova-tabs/commit/d678a7f90f5bd99fba8c6a282ac4c6596c8f886d

I just have a little enhanced me here as well. On detail view, i can have fields outside the tabs, those shows me for instance on top of the panel. but on update, it collect it to the tabs and put it in an empty register.

It would be awesome when it would be separated in the update view as well.

Thanks and best wishes,

Simon

**Comment by bajramemini** [comment]
Hello @simonfunk 

Thanks for the suggestion. Will implement it when I got time this week! 👍

**Comment by bajramemini** [comment]
Hello @simonfunk 

![image](https://user-images.githubusercontent.com/3426944/52180482-13862d80-27e7-11e9-9193-58c5801322b0.png)

This is how it will look. Will tag it shortly.

Regards

**Comment by simonfunk** [comment]
Genius!! Thanks you very much for your work!
