### ISSUE TITLE
Issue with belongsToRelations in version 1.4.1

### ISSUE THREAD

**Issue by mariusghitoiu** [eminiarts/nova-tabs#142]
After updating to version 1.4.1 with with any version of nova from 3.19* up to 3.22 the following error occurs: 

```
vendor.js?id=f0fd4e570967fbf04e26:1 TypeError: Cannot read property 'attribute' of undefined
    at belongs-to-dependency:1
    at Array.forEach (<anonymous>)
    at a.queryParams (belongs-to-dependency:1)
    at hn.get (vendor.js?id=f0fd4e570967fbf04e26:1)
    at hn.evaluate (vendor.js?id=f0fd4e570967fbf04e26:1)
    at a.queryParams (vendor.js?id=f0fd4e570967fbf04e26:1)
    at a.getAvailableResources (app.js?id=f8c78f75999edbef7251:1)
    at a.initializeComponent (app.js?id=f8c78f75999edbef7251:1)
    at a.mounted (app.js?id=f8c78f75999edbef7251:1)
    at It (vendor.js?id=f0fd4e570967fbf04e26:1)


This doesn't happen with version 1.3.*

**Comment by RVxLab** [comment]
I'm gonna need a bit more info on this one.

Is this with a built in field of Nova or an external package?

**Comment by mariusghitoiu** [comment]
This is a nova field, a the belongsTo field. 
I basically have this dropdown which should populate with a list of Counties. 

<img width="1215" alt="Screen Shot 2021-02-17 at 1 12 01 PM" src="https://user-images.githubusercontent.com/147089/108196400-bf2a1e00-7121-11eb-9d0c-3a9479af7719.png">

Here is the code to create the field. 

<img width="908" alt="Screen Shot 2021-02-17 at 1 11 30 PM" src="https://user-images.githubusercontent.com/147089/108196326-a883c700-7121-11eb-8e81-1dcff1994981.png">

With nova-tabs 1.4.* dropdown doesn't get populated and the error added in issue description occurs. 

With nova-tabs 1.3.* it works

**Comment by RVxLab** [comment]
Alright thanks for the report. I'll take a look.

**Comment by mariusghitoiu** [comment]
Thank you for looking into it.

**Comment by RVxLab** [comment]
I had a look and I'm unable to reproduce the issue with the information you gave.

Can you provide a minimal example that can reliably reproduce the issue?

**Comment by RVxLab** [comment]
Closed due to inactivity. Please reopen is this is still an issue for you.
