### ISSUE TITLE
2nd Tab group onwards doesn't work from nova-tabs 1.4.0 onwards

### ISSUE THREAD

**Issue by ziming** [eminiarts/nova-tabs#143]
2nd Tab group onwards doesn't work from nova-tabs 1.4.0 onwards

I'm on nova 3.22

See screenshot below (1st tab group worked, 2nd tab group doesn't and it's just stacked vertically). I had to downgrade to nova-tabs 1.3.1 temporarily

https://share.getcloudapp.com/kpu7nQnB

**Comment by RVxLab** [comment]
Please provide a minimal example for me to reproduce this.

**Comment by ziming** [comment]
Here you go. The fields method

https://share.getcloudapp.com/GGu6pL82

**Comment by RVxLab** [comment]
Not what I meant, but figured it had something to do with Morphs so I created a many-to-many relation as such:

User - Consumable - Drink

Migrations look as follows:

```php
Schema::create('users', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->string('email')->unique();
    $table->timestamp('email_verified_at')->nullable();
    $table->string('password');
    $table->string('photo')->nullable();
    $table->rememberToken();
    $table->timestamps();
});

Schema::create('drinks', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->boolean('is_carbonated');
    $table->timestamps();
});

Schema::create('consumables', function (Blueprint $table) {
    $table->id();
    $table->foreignIdFor(User::class);
    $table->morphs('consumable');
    $table->timestamps();
});
```

Tab shows up as expected:

![image](https://user-images.githubusercontent.com/46111684/108256945-67f66e80-715e-11eb-80f1-5480e9f3da76.png)

I really need a minimal **code** example with steps to reproduce the issue.

Additionally, any JS errors would be very helpful.

**Comment by ziming** [comment]
Hi,

Here is more code

https://share.getcloudapp.com/4gu1K0rG

And here is a bigger screenshot

https://share.getcloudapp.com/9Zu8meRy

As you can see in the screenshot above, after the 1st tab group. from the 2nd tab group onwards it just goes vertically down instead of being proper tab items. When I downgrade to nova tabs 1.3.1 it works again. But not on 1.4.0 and above.

Hope it helps!

**Comment by RVxLab** [comment]
This all should look like it should work. Your tabs are in a format that’s supported. 

Are those panels nested? If they are, please explain in what way. While nested panels should be supported, I didn’t test for that. 

I’m suspecting that this is a client side error. Are you getting JS errors? If so, can you compile Nova’s assets in for development and send me the errors in the console? 

On top, what browser are you using?

**Comment by ziming** [comment]
The panels are not nested, the method calls (e.g. $this->userFields()) simply returns an array of fields.

Hmm how do i compile nova assets in development? For now i just check browser console in production & my machine & there are no browser console errors.

**Comment by RVxLab** [comment]
If you’re not getting console errors then it’s unlikely to be a JS error. I’m releasing a small patch tonight which will fix a tab selection issue. 

If that doesn’t fix your issue then I need you to provide me a minimal **code** example with exact steps to reproduce your issue. 

Please stop sending screenshots of code.

**Comment by RVxLab** [comment]
I just published v1.4.2 which fixes an issue with multiple tabs causing only 1 tabs panel to show up if any tab is selected.

I believe this may fix your issue. If it does not, please reopen this.

**Comment by ziming** [comment]
I can confirm 1.4.2 does not fix this issue

**Comment by RVxLab** [comment]
Then please provide me a code example with a reliable way to reproduce this.

Do not send me a screenshot.

**Comment by ziming** [comment]
My friend will invite you to a private repo later. Thanks!

**Comment by RVxLab** [comment]
I cloned your repo and had a look, but nothing seemed strange here.

In the code you had the following comment

```
// Somehow I need this or I get a Only listable fields or Panel allowed error as an early new Tabs is declared
```

But that message was removed in [this commit](https://github.com/eminiarts/nova-tabs/commit/6f1c9d4121828ef7aac52eebdc4fca06ec38cf88#diff-5cb860a8d1d627d1af91ddf54561464639c71057c036d484c5220edd661cb8ffL70).

Furthermore I have not been able to reproduce your issue, it all looks fine to me.

The private repo you sent was very helpful. Next time you might want to include some seeders for a more accurate reproduction. 

See below screenshots taken in Firefox 86 and Chromium 88.

![localhost_8000_nova_resources_users_1](https://user-images.githubusercontent.com/46111684/110240718-84abe800-7f4d-11eb-98c8-f59d6b4ffb21.png)
![localhost_8000_nova_resources_users_1 (1)](https://user-images.githubusercontent.com/46111684/110240719-85447e80-7f4d-11eb-8ff3-b18f80fe2104.png)
![Screen Shot 2021-03-07 at 13 42 32-fullpage](https://user-images.githubusercontent.com/46111684/110240720-85dd1500-7f4d-11eb-8880-276a84a5217d.png)
![Screen Shot 2021-03-07 at 13 59 55-fullpage](https://user-images.githubusercontent.com/46111684/110240721-85dd1500-7f4d-11eb-947e-e05847b8207e.png)

With this, unless you can provide me a way to reproduce it, I don't think I can help you. Until then I'll be closing this issue.

**Comment by stephanus-stuff** [comment]
as you can see from your screenshoot, in 1.4 it stacked, expected result is like in the yellow circle (1.3)
![image](https://user-images.githubusercontent.com/52034225/110278469-e2056f00-8009-11eb-8b0c-bf5eb71e6c59.png)

**Comment by RVxLab** [comment]
Remove the wrapping array or put every field in its own array/Tab.
