### ISSUE TITLE
Trait makeable not found

### ISSUE THREAD

**Issue by OmarMarie** [eminiarts/nova-tabs#144]
Trait 'Laravel\\Nova\\Makeable' not found at /var/www/laravel/dashboard/vendor/eminiarts/nova-tabs/src/Tab.php:20

**Comment by RVxLab** [comment]
This is not particularly helpful. 

Make sure the trait exists or provide more info.

**Comment by OmarMarie** [comment]
[](url)

**Comment by kfvit-andreaskviby** [comment]
Hey, this has just happened to me as well. 

[2021-03-07 12:57:24] local.ERROR: Trait 'Laravel\Nova\Makeable' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Trait 'Laravel\\Nova\\Makeable' not found at /Users/andreaskviby/Code/wulffcrm2/vendor/eminiarts/nova-tabs/src/Tab.php:20)

There is nothing except Laravel Nova that has been updated and this happens.

If I go into the Tab.php file and just comment out the use Makeable trait it works as nothing has happened but on production server this handy little fix does not work.

I have just published a large update to our CRM and this breaks all company pages inside Nova using Tabs. Do you have any idea on how to fix this.

**Comment by RVxLab** [comment]
@kfvit-andreaskviby What version of Nova are you using?

I would've checked the sources in the repo, but they're no longer accessible.

2 people with this issue makes me think I'm targeting a version of Nova higher than intended.

**Comment by kfvit-andreaskviby** [comment]
Hey there!
I believe this is something that will occur on an old version of Nova but still you will have to remove the use Makeable on new versions of Nova to make your tabs work as intended.

I am nov using Laravel Nova 2.12 and when removing use Makeable in Tab.php it works.

**Comment by RVxLab** [comment]
> I am nov using Laravel Nova 2.12

More or less what I was suspecting. I didn't realize that Makeable wasn't available until some time in 3.x.

Please check the referenced commit above, I'll publish 1.4.3 soon.

**Comment by kfvit-andreaskviby** [comment]
Fantastic work! Both here and on Filament :)

**Comment by RVxLab** [comment]
Thanks! But I don't do anything on Filament (yet).

**Comment by kfvit-andreaskviby** [comment]
Ah, okey. My misstake :)

**Comment by RVxLab** [comment]
I just tagged 1.4.3 that fixes this issue.

I'm sorry for the inconvenience this caused, I was not aware that `Makeable` was not available until 3.x.
