### ISSUE TITLE
Please add overflow-x-auto and search field overlapping.

### ISSUE THREAD

**Issue by tanthammar** [eminiarts/nova-tabs#15]
Great work!!
Could you please add overflow-x-auto.
For wide tabs on tablets and smaller devices it is impossible to reach tabs that grows out of the view.
Also the search field overlaps the tab titles, 
(don't have a suggestion for how to solve that at the moment :)
````
<div class="relationship-tabs-panel card overflow-hidden overflow-x-auto">
````

<img width="889" alt="small screen adjustments" src="https://user-images.githubusercontent.com/21239634/51858796-d7aa1e80-2335-11e9-844f-2017a378f230.png">

**Comment by bajramemini** [comment]
Hello @tanthammar 

I will try to fix the other issues and then tag a new version.

This is how it will look:
![image](https://user-images.githubusercontent.com/3426944/52049174-69d83f80-254d-11e9-8f52-530823e03637.png)

![image](https://user-images.githubusercontent.com/3426944/52049185-7066b700-254d-11e9-8706-5bc54ff1109a.png)

Regards
Bajram

**Comment by swikrit** [comment]
> 
> I will try to fix the other issues and then tag a new version.
> 

Your fix idea looks great! However, I'm still experiencing the issue. I was wondering if it has been released or is it still in the pipeline? 

Do I need to use a particular setting for it to work?

We're in no rush as this is an admin only feature, but I was wondering in case we were just not doing something correctly
