### ISSUE TITLE
Tab doesn't display

### ISSUE THREAD

**Issue by semsphy** [eminiarts/nova-tabs#151]
Hello There,

Currently, I'm using the `nova v3.25.0`, I have no way out to this problem, it is very obvious just follow the README, but I have no luck to get it works.

I just copied and pasted it into my resource, and I got this output without tabs and checked there is javascript error or any exception.

![image](https://user-images.githubusercontent.com/423396/118249722-e2215f80-b4cf-11eb-84c8-5a1c69ad2620.png)

Anyone experienced this problem? Really appreciate!

**Comment by RVxLab** [comment]
What does your fields method look like?

**Comment by semsphy** [comment]
@RVxLab  it is super simple, I just copied from README.

```php
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {

            return [
                Tabs::make('Tabs', [
                    Tab::make('Balance', [
                        Number::make('Balance', 'balance'),
                        Number::make('Total', 'total'),
                    ]),
                    Tab::make('Other Info', [
                        Number::make('Paid To Date', 'paid_to_date')
                    ]),
                ]),

            ];
    }
```

**Comment by RVxLab** [comment]
This looks perfectly fine. This is giving me the idea the JS isn't loading correctly. Please double check the console.

**Comment by sp4r74cus** [comment]
i get exactly the same. no errors in the console. and the script is loading fine via nova-api url. (/nova-api/scripts/tabs)

Nova v 3.25.0
php 7.4

**Comment by semsphy** [comment]
> This looks perfectly fine. This is giving me the idea the JS isn't loading correctly. Please double check the console.

I did check and there was no error in the console.

**Comment by semsphy** [comment]
> i get exactly the same. no errors in the console. and the script is loading fine via nova-api url. (/nova-api/scripts/tabs)
> 
> Nova v 3.25.0
> php 7.4

Mine is on PHP 8.0.3 and Nova v3.25.0

**Comment by RVxLab** [comment]
Over the weekend I also managed to run into this issue on Nova 3.25, but wasn't able to find a cause. 

I'd be more than willing to accept a PR for this as this is incredibly confusing and I don't really have the time to look into it.

**Comment by semsphy** [comment]
Understood and really appreciate!

**Comment by semsphy** [comment]
> Over the weekend I also managed to run into this issue on Nova 3.25, but wasn't able to find a cause.
> 
> I'd be more than willing to accept a PR for this as this is incredibly confusing and I don't really have the time to look into it.

FYI, I am using your tab in [nova-settings](https://github.com/optimistdigital/nova-settings) and it works fine.

**Comment by Blindmikey** [comment]
Is TabsOnEdit being used?

**Comment by hashmaldives** [comment]
Works well with [Optimist Digital Nova Settings Package](https://github.com/optimistdigital/nova-settings) but does not render tabs on a default nova resource. Any solution for this?

**Comment by Blindmikey** [comment]
Once my Resource used TabsOnEdit this issue was resolved. Is this not the case in your usage? 
```php
// in app/Nova/Resource.php

use Eminiarts\Tabs\Tabs;
use Eminiarts\Tabs\TabsOnEdit; // Add this Trait

class Client extends Resource
{
    use TabsOnEdit; // Use this Trait
    //...
}
```

**Comment by hashmaldives** [comment]
> Once my Resource used TabsOnEdit this issue was resolved. Is this not the case in your usage?
> 
> ```
> use Eminiarts\Tabs\Tabs;
> use Eminiarts\Tabs\TabsOnEdit; // Add this Trait
> 
> class Client extends Resource
> {
>     use TabsOnEdit; // Use this Trait
>     //...
> }
> ```

Works perfectly. Thank you :)

**Comment by valentinfily** [comment]
In my case I fixed the issue by adding the service provider to app.php in config folder as such :
```
'providers' => [
   ...
   Eminiarts\Tabs\TabsServiceProvider::class,
]
```

**Comment by RVxLab** [comment]
By the looks of it this issue has been fixed, I'll close it.
