### ISSUE TITLE
Not access to current resource on edit in fields() method

### ISSUE THREAD

**Issue by mgralikowski** [eminiarts/nova-tabs#152]
```php
    /**
     * use TabsOnEdit;
     * 
     * Get the fields displayed by the resource.
     *
     * @param  Request $request
     * @return array
     */
    public function fields(Request $request): array
    {
        // dd($this->model(), $this->resource); // dump same - empty eloqent model

        return [
            Tabs::make('Tabs', [
                Tab::make('Basic information', [
                    new Panel('Basic information', $this->basicFields()),
                    ...
                ]),
            ]),
        ];
    }
```

I losing access to resource objects during validation (updating action in nova) when I use the `TabsOnEdit` trait, under the property, the eloquent model is still there but empty. Removing trait makes it works again. Resource object is helpful, for example, I would use it as an exception in a unique rule.

**Comment by RVxLab** [comment]
I’ve seen something happen like this before during the use of actions, so I’m a bit doubtful this is due to the trait. 

Can you provide some more info on this? What exactly did you do to come to this conclusion?
