### ISSUE TITLE
Version 1.4.5 No tab render

### ISSUE THREAD

**Issue by julianpoma** [eminiarts/nova-tabs#156]
After update to 1.4.5 the tabs dissapear. Downgrade to 1.4.4 and clear cache in browser the tabs render OK.

**Comment by RVxLab** [comment]
Agh I must have messed something up in the production build. Sorry about that. I’ll make a fix as soon as I can.

**Comment by RVxLab** [comment]
Really odd. The tab on edit works fine but on the details page it's not showing up. No console errors.

**Comment by RVxLab** [comment]
Had a further look but I can't seem to find a clear cause. When I build Nova for development or production by hand it works fine. It might be something with the build process but I don't know at this time.

Keep downgraded to 1.4.5 for now. I'll need to take a look later.

**Comment by RVxLab** [comment]
My observations so far:

- The tab component is mounting
- The root div is rendered
- The rest of the template is not being rendered

**Comment by mstaack** [comment]
Same here, latest 1.4.5 version shows no tabs anymore

**Comment by RVxLab** [comment]
> Same here, latest 1.4.5 version shows no tabs anymore

Downgrade to 1.4.4 for now.

**Comment by RVxLab** [comment]
I released 1.4.6 to address this issue, upgrade to that.

Until a future release the changes introduced with #155 won't be available.

**Comment by ThaDaVos** [comment]
Seems to be broken on 1.5.x again - downgraded to 1.4.6

**Comment by RVxLab** [comment]
See #172

**Comment by ThaDaVos** [comment]
Yeah that's whats happening - weird that I couldn't find that issue

**Comment by RVxLab** [comment]
I honestly have no idea what's causing this, I'm thinking it's a Nova issue that's outside of my control.
