### ISSUE TITLE
Cannot delete files from file fields

### ISSUE THREAD

**Issue by PCodrin** [eminiarts/nova-tabs#158]
![image](https://user-images.githubusercontent.com/6823415/125467068-44ba46b6-6e68-43ce-90ff-82687d810d32.png)

**Comment by PCodrin** [comment]
![image](https://user-images.githubusercontent.com/6823415/125466654-1e26ae7d-a420-47e9-b3f4-27ea3f4d34f0.png)

**Comment by RVxLab** [comment]
I fail to see how this is caused by nova-tabs. You have a 404, sounds like a problem within your resource.

**Comment by PCodrin** [comment]
That occurs when you add a File field in a tab just try to see if it works. Thanks!

**Comment by Kenny201** [comment]
Got the same problem. Does anybody know how to fix it?

**Comment by arlon23** [comment]
@Kenny201 @PCodrin I did this change on updateFields and creationFields and seems to fix the problems, I didin't make all the tests on my project, but if you want to try and test on your projects, after I finish with my test I will make a PR.

![image](https://user-images.githubusercontent.com/45430368/146773922-534b1f17-e95f-401d-81c1-c88bd84ff12a.png)

**Comment by RVxLab** [comment]
This should be fixed with #169. I’ll make a release towards the weekend.

**Comment by RVxLab** [comment]
Version 1.5.0 has been released which should address this issue.
