### ISSUE TITLE
h1 heading is set to display:none

### ISSUE THREAD

**Issue by MHassanSaqib** [eminiarts/nova-tabs#159]
I have noticed that the h1 heading is set to `display: none`, I couldn't notice any impact of this class on the tabs, is it redundant?. It is breaking the quilljs editor. Might also impact other functionality or packages.

```
.relationship-tabs-panel h1 {
    display: none;
}
```

**Comment by RVxLab** [comment]
It's entirely possible that it's redundant, but I'm not able to say for sure.

If you can find evidence that this is a dedundant selector I'd gladly accept a PR for it.

**Comment by Broutard** [comment]
impact editorjs package too.
