### ISSUE TITLE
Bug with Filters and little results

### ISSUE THREAD

**Issue by brunogaspar** [eminiarts/nova-tabs#16]
Hey

This is 2 reports in 1, since they are connected.

![screen shot on 2019-01-30 at 22-52-41](https://user-images.githubusercontent.com/2285372/52018296-d3226900-24e1-11e9-82d8-f47aa4072501.png)

1. As you can see from the screen above, if i have one result the filters get's cut out and i need to scroll that list but while that might work, the last filter is almost unreachable.

2. Another problem is if have many tabs and i have filters with only one result (same as above) this time i can't scroll it.

Not sure if that's easily fixable, but that's a bug regardless.

**Comment by bajramemini** [comment]
Hey @brunogaspar 

How are you? 

Removed the overflow (not sure why @enesemini designed it that way) on the relationship-panel. 

Should look like this now:

![image](https://user-images.githubusercontent.com/3426944/52181631-366b0e80-27f4-11e9-8697-36959f49849a.png)

Will tag it shortly. Reopen the issue if there is still a problem. 

Regards

**Comment by brunogaspar** [comment]
Hey @bajramemini 

Just checked, looks way better, thanks a lot :)

Cheers!
