### ISSUE TITLE
issue in TabsOnEdit

### ISSUE THREAD

**Issue by esameisa** [eminiarts/nova-tabs#163]
when i use TabsOnEdit
example i use:
i have user resource and each user has userDetails, the relation is one to one
when i use TabsOnEdit in user resource, it only update user data but didn't update userDetails data

Any Help?

**Comment by Anrail** [comment]
Hi, has anyone solve the problem?
Share your experience =)

**Comment by RVxLab** [comment]
As far as I know this isn’t supported by Nova. You’d need to do a hard refresh of sorts afterwards.

**Comment by RVxLab** [comment]
I'm closing this under the assumption that this isn't something Nova supports. If you find any proof that this is support then please provide me some examples as to how this could be done or provide a PR doing that.
