### ISSUE TITLE
H1 in parent Tabs is truncated with ...

### ISSUE THREAD

**Issue by rbishop2006** [eminiarts/nova-tabs#164]
When providing a title to the Tabs::make('//title//'), the H1 is truncated with ellipsis instead of showing the entire title.  When I inspect it, it shows a css class of .truncate .  Is there an option not to truncate the title?

**Comment by RVxLab** [comment]
The `.truncate` class isn't referenced in the tabs, pretty sure this comes from Nova directly or some other package.

If you find evidence this comes from this package you can reopen this issue.

**Comment by rbishop2006** [comment]
After updating to the most current Nova 3.29.0, the issue on the H1 was fixed.  Thanks for your help.
