### ISSUE TITLE
Dependency Issue starting from tag 1.4.0 

### ISSUE THREAD

**Issue by marlocorridor** [eminiarts/nova-tabs#170]
**Context:**
I'm using Nova v2.
After we update this packages, from "1.2.2" to "1.4.6",

**Issue:**
The method call for `fieldResolverCallback` is `undefined`.

**Solution:**
I fixed it by requiring "1.3.*" of  `eminiarts/nova-tabs` instead.

**Request:**
I do not know how yet but:
- could we add a restriction starting "1.4.0" to require Nova v3?

**Comment by RVxLab** [comment]
Since removing support for Nova 2.x is a BC break this would be better suited for a major bump. 

Honestly though, a 2.x version of this package would best come with Nova 4.0. 

I recommend using your current solution as I have no plans to add support for this.
