### ISSUE TITLE
Relation Tabs disappeared

### ISSUE THREAD

**Issue by norhan-elnezamy** [eminiarts/nova-tabs#172]
I 'm using the relation tabs and it was working fine. but suddenly it stoped without any change in code from my side, I expected it's related to the last released version so, I had to downgrade to version 1.4.6 and then it works fine again .

**Comment by RVxLab** [comment]
Sounds like an issue I found while doing production builds in #157, can you confirm?

**Comment by norhan-elnezamy** [comment]
yes, it seems like it. No tabs appears in details page
<img width="1440" alt="Screen Shot 2022-02-16 at 1 46 50 PM" src="https://user-images.githubusercontent.com/99803377/154259000-41e82394-2414-4301-a1c8-a36c730232c6.png">
<img width="1440" alt="Screen Shot 2022-02-16 at 1 46 41 PM" src="https://user-images.githubusercontent.com/99803377/154259024-01fe1b6d-582d-44a0-933a-8629fce75f30.png">

**Comment by norhan-elnezamy** [comment]
yes, it seems like it. No tabs appears in details page.
![resource](https://user-images.githubusercontent.com/99803377/154259549-ec0a0d89-0efb-42c8-9ccd-8b9bce5013b8.png)
![details-page](https://user-images.githubusercontent.com/99803377/154259558-5d8e3f29-af35-4a60-afe3-56a6e58f2e13.png)

**Comment by RVxLab** [comment]
Strange. I’ll need to research this. Perhaps update the build settings.

**Comment by RVxLab** [comment]
I'm currently unable to reproduce this locally with a fresh production build.

But to hopefully fix this issue can you please do the following:

1. Re-publish your Nova assets with `php artisan nova:publish`
2. Update the nova-tabs package to `dev-improved-frontend-building`

```json
"require": {
    "eminiarts/nova-tabs": "dev-improved-frontend-building"
},
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/eminiarts/nova-tabs"
    }
],
```

Then run `composer update eminiarts/nova-tabs`.

**Comment by elizdlt202** [comment]
Hi, I think I'm having the same issue. The whole content within Tabs::() has disappeared. the screenshot shows what I've been using - and everywhere I'm using it - it does not display at all in the ui. This only happened after the recent version update

![Screen Shot 2022-02-22 at 10 02 56 AM](https://user-images.githubusercontent.com/49735067/155192173-168c7d34-08c0-45a2-b687-fb6ab6fa654a.png)

**Comment by RVxLab** [comment]
> Hi, I think I'm having the same issue. The whole content within Tabs::() has disappeared. the screenshot shows what I've been using - and everywhere I'm using it - it does not display at all in the ui. This only happened after the recent version update
> 
> ![Screen Shot 2022-02-22 at 10 02 56 AM](https://user-images.githubusercontent.com/49735067/155192173-168c7d34-08c0-45a2-b687-fb6ab6fa654a.png)

Can you take the instructions from my previous comment and see if that fixes it?

**Comment by elizdlt202** [comment]
Hi, your previous comment ( solution ) actually didnt work for me.

**Comment by norhan-elnezamy** [comment]
> I'm currently unable to reproduce this locally with a fresh production build.
> 
> But to hopefully fix this issue can you please do the following:
> 
> 1. Re-publish your Nova assets with `php artisan nova:publish`
> 2. Update the nova-tabs package to `dev-improved-frontend-building`
> 
> ```json
> "require": {
>     "eminiarts/nova-tabs": "dev-improved-frontend-building"
> },
> "repositories": [
>     {
>         "type": "vcs",
>         "url": "https://github.com/eminiarts/nova-tabs"
>     }
> ],
> ```
> 
> Then run `composer update eminiarts/nova-tabs`.

the solution works fine with me, thanks a lot for supporting.

**Comment by BertKooij** [comment]
I had the same issue and tried your instructions, sadly it did not seem to fix the issue. But it seems to be related to something that has been changed in Laravel Nova. I was running v3.28.2 and just updated it to the latest version (v3.31.0) which did the trick. The tabs are now being displayed again with version 1.5.0.

**Comment by RVxLab** [comment]
@norhan-elnezamy @BertKooij Thanks for verifying this with me! I’ll release 1.5.1 today with the new dist files.

@elizdlt202 If you’re running an older version of Nova, please update to the latest.

**Comment by RVxLab** [comment]
Version 1.5.1 has been released to address this issue. An update to Nova may be required to fully fix this, unfortunately there's not much I can do about that.

**Comment by elizdlt202** [comment]
Thank you @RVxLab for your quick care on this! Much appreciated! 
I'll try to see if it works again.

**Comment by mziraki** [comment]
@RVxLab
same issue here, even with Nova v3.31.0 and this package v1.5.1!
I tried all the solutions in previous comments!

**Comment by RVxLab** [comment]
Outside of publishing the assets on the latest Nova build I really don't know what else could fix this.

Otherwise please provide a private repository with a minimal example as this is a ridiculously hard issue to reproduce.

**Comment by mziraki** [comment]
@RVxLab
after tracking down the bug commit by commit, I found out upgrade of laravel mix from v1 to v6 break something in code, but I can't find what!
