### ISSUE TITLE
Tabs not showing up when not calling withToolbar

### ISSUE THREAD

**Issue by vpratfr** [eminiarts/nova-tabs#175]
Hi,

When not calling the showToolbar function, the tabs are not showing up on the page.

Using latest versions of Laravel 8, Nova 3 + this package. PHP 8.1 if that matters.

Working

```
            // I have other fields before the tabs

            Tabs::make(trans('nova.documents'), [
                HasMany::make(trans('nova.deliverables'), 'deliverables', MissionDeliverable::class),

                HasMany::make(trans('nova.uploads'), 'uploads', MissionUpload::class),

                HasMany::make(trans('nova.receipts'), 'receipts', MissionReceipt::class),

                MorphMany::make(trans('nova.notes'), 'notes', Note::class),
            ])->withToolbar(),
```

Not working

```
            // I have other fields before the tabs

            Tabs::make(trans('nova.documents'), [
                HasMany::make(trans('nova.deliverables'), 'deliverables', MissionDeliverable::class),

                HasMany::make(trans('nova.uploads'), 'uploads', MissionUpload::class),

                HasMany::make(trans('nova.receipts'), 'receipts', MissionReceipt::class),

                MorphMany::make(trans('nova.notes'), 'notes', Note::class),
            ]),
```

**Comment by RVxLab** [comment]
Are you running the latest version of Nova (3.31 as of right now)?

There have been issues with people not being able to see the tabs when running on previous Nova 3 versions, like in issue #172.

**Comment by vpratfr** [comment]
Hi

Yes we are: 3.31.0

The tabs show up, but not when we do not ask to show the toolbar.

**Comment by RVxLab** [comment]
Sounds like a strange issue. Can you provide a private repo with a minimal example and invite me to it? I can’t reproduce this locally.

**Comment by vpratfr** [comment]
Will check again on Monday, and publish nova assets again to make sure they
are up to date too

**Comment by RVxLab** [comment]
Haha no worries at all! I'm glad you were able to fix it.
