### ISSUE TITLE
H1 of component  not hidden when ->defaultSearch() applied

### ISSUE THREAD

**Issue by cord** [eminiarts/nova-tabs#179]
class `tab-content` is not applied with `->defaultSearch(true)`, so therefore H1 is not hidden as applied through the following css:

````
    .tab-content > div > div[dusk$="-index-component"] > h1 {
        display: none;
    }
````

**Comment by villeneuve-michael** [comment]
My variation for this issue:

In ~/resources/vendor/nova/partials/meta.blade.php
```
<style>
    .relationship-tabs-panel h1 {
        display: none;
    }
</style>
```

**Comment by RVxLab** [comment]
@cord Thanks for the report. I’ll need to take a look. 

@villeneuve-michael That would cause a regression of https://github.com/eminiarts/nova-tabs/issues/159

**Comment by villeneuve-michael** [comment]
Ah you're correct! Thanks for the correction didn't think of that case.
