### ISSUE TITLE
Nova 4.x upgrade

### ISSUE THREAD

**Issue by eduance** [eminiarts/nova-tabs#181]
Hiya,

For Nova 4.x we need to upgrade the package in order to keep using it.

We would love to help. Is this package still maintained? If it is wished, I can start a PR and get going.

**Comment by KickSchutte67** [comment]
Hi @eduance,

As mentioned in this issue opened 13d ago (https://github.com/eminiarts/nova-tabs/issues/180), the maintainer has stopped due several different reasons. 

@RVxLab mentioned: "I'll be helping maintaining the 1.x branch for Nova 3 until someone makes a 4.x version.". So I think you can start working on a new version, as my Nova is also depending on this package.

**Comment by RVxLab** [comment]
Considering Nova 4 is a major release as well I have the idea the whole package will need a rewrite to some extent. So perhaps you could even ask @bajramemini to take over from me if you wish to.

**Comment by eduance** [comment]
@RVxLab That would be really awesome. Our company is looking to help where we can.
@bajramemini Any thoughts into this?

@KickSchutte67 We will be working on a solution to help keeping this package alive.

**Comment by RVxLab** [comment]
Perhaps you could email Bajram, you can find his email on his GitHub profile.

**Comment by acato-dev** [comment]
@RVxLab Alright! I'll be taking over from this account on behalf of Acato.
