### ISSUE TITLE
Nova 4.x upgrade

### ISSUE THREAD

**Issue by acato-dev** [eminiarts/nova-tabs#183]
Hi,

To inform everyone, I'm currently on a different account (I was the starter on the previous topic on a different account) as I am representing Acato and we are looking to take over this package.

I'll start today and we are looking forward to creating a sustainable solution.

We will be requesting @bajramemini to take it over but we would love to do it and have the capacity available.

**Comment by laradevca** [comment]
If I can be of any help let me know. I'd be willing to chip in some time to figure it out as I use this package in almost all of my projects.

**Comment by scramatte** [comment]
Hi, 

We are interested into Nova4 support.  Let me know if you need help
Regards

**Comment by crynobone** [comment]
@Grafikart Creating Panel with custom component has been fixed in 4.2.3, can you review that and see if it does what you needs it to?

**Comment by Grafikart** [comment]
I'm stuck I can't make it work, I cannot get the serialization I want and I moved to another task at the moment. So if someone want to follow up go ahead.

**Comment by scramatte** [comment]
Hi,

I've tried to fix it but I've got the following error:

```
 "message": "Attempt to read property \"component\" on null",
    "exception": "ErrorException",
    "file": "/opt/eom/vendor/laravel/nova/src/Panel.php",
    "line": 91,
```

Regards

**Comment by crynobone** [comment]
https://github.com/eminiarts/nova-tabs/blob/cd19cf4954c54ba18ecdff7c1f7fdfb83cc23252/src/Tabs.php#L55-L57

It should also include `$field->assignedPanel = $this;`

**Comment by marcfilipan** [comment]
#185 I got it working, but removed a bunch of the options, as I simply don't need them.

**Comment by bajramemini** [comment]
Hello @acato-dev 

We've been busy with other projects and non Nova-related stuff and didn't have the time/project yet to use this with v4.

We would be happy to add some collaborators/maintainers to this package.

You could tell me which users are going to be involved and should be added as collaborators.

Kind regards

**Comment by marcfilipan** [comment]
I actually have an idea about that, but have to discuss it with someone else first, I'll get back to you in a couple of hours.

**Comment by marcfilipan** [comment]
Fixed with https://github.com/eminiarts/nova-tabs/releases/tag/2.0.0
