### ISSUE TITLE
Optimize the loading time 

### ISSUE THREAD

**Issue by parth-ka-patel** [eminiarts/nova-tabs#184]
i am using nova-tabs and i am facing the issue to taking more time to load full page so i suggest to if you are changed that when user click on that particular tab on first time then that page contents are load otherwise only first tab data display 

each and every tab works like this if i am select 2nd tab then that data are load so it'll reduce lot of time to load the data

**Comment by parth-ka-patel** [comment]
@RVxLab  Please look into this and if have any solution then it's great to use

**Comment by RVxLab** [comment]
Tabs don't load things on their own, that's handled by the underlying relations. So I don't think this is an issue with nova-tabs, but rather an issue with your queries.

Please check that first.

**Comment by parth-ka-patel** [comment]
I am just suggesting if this possible from your side then it'll benefited to all

**Comment by RVxLab** [comment]
Ah I see, my bad.

With Nova 4 being out and my stepping down as maintainer (#180) this is not something I'm looking at implementing. With the version for Nova 4 (which I expect to be a 2.x release) this could be a feature.

Besides, with proper Eloquent optimization this shouldn't be needed.

**Comment by parth-ka-patel** [comment]
> Ah I see, my bad.
> 
> With Nova 4 being out and my stepping down as maintainer (#180) this is not something I'm looking at implementing. With the version for Nova 4 (which I expect to be a 2.x release) this could be a feature.
> 
> Besides, with proper Eloquent optimization this shouldn't be needed.

Okay Thank you so much but if you find any solution for this 2 question so please share here .
Thanks again

**Comment by marcfilipan** [comment]
In the 2.0.0 version for Nova 4, fields within tabs are only loaded once the tab has been opened. That being said, regular field data is always loaded, but if you use relational fields, they will only load data once the tab has been opened as the function to fetch their data is only triggered once the tab has been opened. 

Let me know if that's enough.
