### ISSUE TITLE
Nova tabs 2.0 does not show toolbar on first generated panel when only relation tab is used

### ISSUE THREAD

**Issue by rderks88** [eminiarts/nova-tabs#189]
First of all, thank you guys so much for upgrading to support nova 4.0! You helped me lots.
Will also submit a PR for this issue asap:

When tabs is only used for relations, it is impossible to show the toolbar on the first panel.
This should default to the normal nova behavior and show a toolbar on the first panel that includes all "normal" fields.

To reproduce:

```
class Author extends Resource
{
    use HasTabs;

    public function fields(NovaRequest $request)
    {
        return [
            Text::make('name'),

            Tabs::make('Relations', [
                    HasMany::make('books'),
            ]),
        ];
    }
}
```

**Comment by marcfilipan** [comment]
https://github.com/eminiarts/nova-tabs/releases/tag/2.0.1
