### ISSUE TITLE
Nova settings compatibility

### ISSUE THREAD

**Issue by stepanenko3** [eminiarts/nova-tabs#192]
Tabs are not displayed on settings page [outl1ne/nova-settings](https://github.com/outl1ne/nova-settings.git)

**Comment by marcfilipan** [comment]
https://github.com/outl1ne/nova-settings/blob/e2414f5be57f0328129cf03d2337d91e115b590b/resources/js/views/Settings.vue

He has it commented out.

**Comment by stepanenko3** [comment]
@marcfilipan but the old way to identify nova-tabs in the new version no longer works
I tested it, and I didn't find any signs of tabs in js
