### ISSUE TITLE
MorphToMany Relationship 

### ISSUE THREAD

**Issue by ahmedkandel** [eminiarts/nova-tabs#2]
For MorphToMany Relationship the Tab changes "Attache Resource" button to "Create Resource" then when click create it gives error as explain in #1

**Comment by bajramemini** [comment]
Hello @ahmedkandel 

Thanks for pointing this out.

#1 is fixed now. So the "Create" Button should work now. Not sure why it changes "Attach Resource" to "Create Resource". 

Will try to solve it tomorrow and let you know what I came up with.

Regards,
Bajram

**Comment by ahmedkandel** [comment]
Thanks @bajramemini
