### ISSUE TITLE
Tabs not working with custom resource tools

### ISSUE THREAD

**Issue by ralbeary** [eminiarts/nova-tabs#20]
I have a working resource tool but when i setup the tabs, the resource tool title aperas as the tab title and nothing inside.

Code in the resource:
```PHP
new Tabs('Tabs', [
                'Details' => [
                    ID::make()->sortable(),

                    Text::make('First name', 'firstName')
                        ->sortable()
                        ->rules('required', 'max:255'),
                    
                    Text::make('Last name', 'lastName')
                        ->sortable()
                        ->rules('required', 'max:255'),

                    Text::make('Email')
                        ->sortable()
                        ->rules('required', 'email', 'max:254')
                        ->creationRules('unique:users,email')
                        ->updateRules('unique:users,email,{{resourceId}}'),

                    Password::make('Password')
                        ->onlyOnForms()
                        ->creationRules('required', 'string', 'min:6')
                        ->updateRules('nullable', 'string', 'min:6'),
                ],
                'Permissions' => [
                    NovaUserPermissions::make(),
                ],
            ]),
```
Capture of the tab:

![screen shot 2019-02-08 at 18 16 37](https://user-images.githubusercontent.com/44970830/52497341-c1ba1a80-2bcd-11e9-8d30-55a3945377ed.png)

Error in the chrome console:
```
vendor.js?id=9e34ca4c58232cf1ad19:94149 [Vue warn]: Unknown custom element: <detail-nova-user-permissions> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <DetailTabs>
       <LoadingView> at resources/js/components/LoadingView.vue
         <Detail> at resources/js/views/Detail.vue
           <Root>
```

**Comment by bajramemini** [comment]
Hello @ralbeary 

Seems like it has nothing to do with the Tabs package but rather the Nova User Permissions. Is there a `<detail-nova-user-permissions \>` component? Which package are you using? 

If I know which package you are using, I could try to reproduce the error.

**Comment by ralbeary** [comment]
Hi @bajramemini , that `<detail-nova-user-permissions \>` component is a custom one i made without any special feature. I made it with the `nova:resource-tool` cli helper.

If i remove all the lines related to the tabs, all the fields, even the custom component, is showed correctly.

![screen shot 2019-02-11 at 09 31 58](https://user-images.githubusercontent.com/44970830/52555012-775cb780-2de0-11e9-9ecd-069d37270f8e.png)

```PHP
return [
    ID::make()->sortable(),

    Text::make('First name', 'firstName')
        ->sortable()
        ->rules('required', 'max:255'),

    Text::make('Last name', 'lastName')
        ->sortable()
        ->rules('required', 'max:255'),

    Text::make('Email')
        ->sortable()
        ->rules('required', 'email', 'max:254')
        ->creationRules('unique:users,email')
        ->updateRules('unique:users,email,{{resourceId}}'),

    Password::make('Password')
        ->onlyOnForms()
        ->creationRules('required', 'string', 'min:6')
        ->updateRules('nullable', 'string', 'min:6'),

    NovaUserPermissions::make(),
];
```

**Comment by bajramemini** [comment]
@ralbeary 

Did you create it as a Tool or as a Field?

Fields usually follow the convention "detail-component-name" and "form-component-name"...

That's why it is looking for `<detail-nova-user-permissions>`

If it is your own tool, would you mind registering it correctly:

```
Vue.component('detail-nova-user-permissions', require('./components/NovaUserPermissions'));
```

**Comment by dkulyk** [comment]
@bajramemini https://github.com/dkulyk/nova-tabs/commit/589cfd88a3ce0ac95019e145f05b50e6618d946d
Allows use resource tools.

**Comment by bajramemini** [comment]
thanks @dkulyk going to merge that in here too! Much appreciated, thanks!

**Comment by slavicd** [comment]
Why has this been closed without actually being fixed?
