### ISSUE TITLE
On validation error, did not jump to the right tab with the validation error

### ISSUE THREAD

**Issue by ziming** [eminiarts/nova-tabs#205]
In the previous major version of this package, if there is a validation error, it will jump to the right tab, highlight it red and show the field with the error. You can be on a different tab and all these still happen.

In the latest major version, if there is a validation error, it just say there is a problem, but did not jump to the right tab. did not highlight it red, did not scroll down to the field with the validation error

**Comment by marcfilipan** [comment]
And what would it do if there is a validation error on multiple tabs?

**Comment by ziming** [comment]
Hmm I have since merged my nova 4 branch to master. Hard to reverse now.

But i suppose you can switch to the 1st tab with the 1st validation error

For other tabs, maybe highlight the header red too to indicate they also have validation errors, I'm not sure

Maybe @RVxLab can answer how it is like in the previous major version.

**Comment by RVxLab** [comment]
> Hmm I have since merged my nova 4 branch to master. Hard to reverse now.
> 
> But i suppose you can switch to the 1st tab with the 1st validation error
> 
> For other tabs, maybe highlight the header red too to indicate they also have validation errors, I'm not sure
> 
> Maybe @RVxLab can answer how it is like in the previous major version.

In Nova 3 it was done by checking if any tab contained an error and if so jump to the first one that had one.

See https://github.com/eminiarts/nova-tabs/blob/1.5.1/resources/js/components/FormTabs.vue#L86 and 
https://github.com/eminiarts/nova-tabs/blob/1.5.1/resources/js/components/FormTabs.vue#L149

@marcfilipan Perhaps this can help you out with making a modern implementation?

**Comment by marcfilipan** [comment]
It doesn't jump to the tab that has an error, as that can simply be multiple ones, but does mark them as having errors now.

**Comment by marcfilipan** [comment]
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/1815234/168275512-ac89a631-aa53-4417-bfa7-7471c0792550.png">
