### ISSUE TITLE
Ugly styling on active tabs since v2.0.5

### ISSUE THREAD

**Issue by LTKort** [eminiarts/nova-tabs#209]
On 2.0.3 the tabs looked like this:
<img width="567" alt="Screenshot 2022-05-13 at 15 40 57" src="https://user-images.githubusercontent.com/2412670/168297225-1a8f9808-0805-4646-8402-741f16059377.png">

Now on 2.0.5 it looks like this, which in my opinion is a lot worse:
<img width="546" alt="Screenshot 2022-05-13 at 15 45 08" src="https://user-images.githubusercontent.com/2412670/168297278-e16b0922-4ccc-449a-8cd2-ca1915620c9f.png">

Can this be reverted? The cause is on FormTabs.vue on line 29 with the following class 'tabs-border-2', my suggestion is to do a border-b

**Comment by marcfilipan** [comment]
Should be fixed in 2.0.6

**Comment by LTKort** [comment]
@marcfilipan Thanks, the border is now better. Only the color... why the default Sky? 
Cant we just use the default primary color from the Nova config? Now we need to add a function for all resources where has tabs..

**Comment by marcfilipan** [comment]
I could make it later tonight that I uses a config file where you can configure them globally if that's preferred.

**Comment by LTKort** [comment]
I think the most logical solution is to use the defaults from Nova and overwrite them using a function. 
I will do a fork and give it a go.

**Comment by marcfilipan** [comment]
Can't use the defaults, primary doesn't exist in nova-tabs, so can only load what is parsed by tailwind in Nova, border-b-primary-500 isn't in there, border-primary-500 is, but then you get the original issue.

**Comment by LTKort** [comment]
I’ve been at it and think i have a solution

**Comment by LTKort** [comment]
If a color is configured in the function it will work as it does right now. But if there is not a color defined the classes are not prefixed with ‘tabs-‘ and the primary color will be used

**Comment by marcfilipan** [comment]
I'll repeat, border-b-primary-500 is purged from novas tailwind, as they don't use it. That means we can't use it, we can potentially use the var though and create a class in css for it.

**Comment by LTKort** [comment]
@marcfilipan Thanks for the input, I did a PR #212 which fixes the problem you mentoined

**Comment by marcfilipan** [comment]
I merged the PR from @ianrobertsFF, it's a cleaner fix.

Thanks for all the work guys!

**Comment by ianrobertsFF** [comment]
The one you merged was the fixes for the history state issues and edit cancel functionality

I was still testing this one (My test project was still on default Nova colours), will PR it now

**Comment by LTKort** [comment]
But you are overriding TW classes

**Comment by ianrobertsFF** [comment]
This is true, I am overriding a very specific Nova tailwind class (primary isnt a colour available in TW itself) to do exactly the same thing that the class would do if it were implemented by the distributed Nova TW implementation.
