### ISSUE TITLE
Method mutate does not exist

### ISSUE THREAD

**Issue by KakaDemon** [eminiarts/nova-tabs#216]
`laravel/nova:v4.2.0`
Code:
```
Tabs::make('Some Title', [
    Tab::make('Balance', [
        Number::make('Balance', 'balance'),
    ]),
    Tab::make('Other Info', [
        Number::make('Paid To Date', 'paid_to_date')
    ]),
]),

```
Got this error
<img width="572" alt="2022-05-19 in 22 00 25" src="https://user-images.githubusercontent.com/4408551/169357217-38e18377-dd82-404c-a20a-9f0d5ba7fce7.png">

**Comment by mstaack** [comment]
Did you add the trait?

**Comment by KakaDemon** [comment]
Yes
<img width="1232" alt="2022-05-19 in 23 27 05" src="https://user-images.githubusercontent.com/4408551/169373672-21cce987-7be1-4835-bc11-d601e46ec8b8.png">

**Comment by marcfilipan** [comment]
Which version of Nova are you using?

**Comment by KakaDemon** [comment]
Yes, fixed after update nova.
Thanks
