### ISSUE TITLE
CSS error on Relationship

### ISSUE THREAD

**Issue by Giactan** [eminiarts/nova-tabs#22]
Buttom Border not display correctly in Relationships
![screen shot 2019-02-24 at 1 08 06 pm](https://user-images.githubusercontent.com/31847606/53295789-83f7fb80-3835-11e9-8103-a28d044290e6.png)
Code:
![screen shot 2019-02-24 at 1 10 24 pm](https://user-images.githubusercontent.com/31847606/53295792-92461780-3835-11e9-9c6b-a9ae82a5e77c.png)

**Comment by XternalSoft** [comment]
Maybe same issue but with tab that contains relationship 

Tab with BelongsTo :
![capture d ecran de 2019-02-24 17-18-40](https://user-images.githubusercontent.com/1142472/53301893-625c3b80-3858-11e9-8792-862f6f2e469f.png)

![capture d ecran de 2019-02-24 17-19-35](https://user-images.githubusercontent.com/1142472/53301894-65572c00-3858-11e9-91a4-5fd69e889cea.png)

Correct tab (at right) :
![capture d ecran de 2019-02-24 17-18-06](https://user-images.githubusercontent.com/1142472/53301880-4d7fa800-3858-11e9-9f39-b0dfceae68b5.png)

**Comment by bajramemini** [comment]
I think this should be fixed by now.

If there is any further issue, feel free to reopen the issue.
