### ISSUE TITLE
Not working in Nova v4.7.0

### ISSUE THREAD

**Issue by RealityGamin** [eminiarts/nova-tabs#220]
I followed the first example to test this out on a fresh Nova installation

It will not show any tabs in the top area, rather it will show whatever field you make inside the table itself.

![image](https://user-images.githubusercontent.com/100086757/171618260-952596cb-c0cf-4f9c-a445-4ffa2294a3f5.png)
![image](https://user-images.githubusercontent.com/100086757/171618423-368ea748-2031-414e-bc2b-5307ecdcd9e0.png)

Please help resolve this issue :)

**Comment by RealityGamin** [comment]
any ideas?

**Comment by marcfilipan** [comment]
None whatsoever, can you try it in the following way and see if it works?

`use Eminiarts\Tabs\Traits\HasTabs;
use Eminiarts\Tabs\Tabs;
use Eminiarts\Tabs\Tab;

class User extends Resource
{
    use HasTabs;
    
    public function fields(Request $request)
    {
       return [
         Tabs::make('Some Title', [
            Tab::make('Balance', [
                Number::make('Balance', 'balance'),
                Number::make('Total', 'total'),
            ]),
            Tab::make('Other Info', [
                Number::make('Paid To Date', 'paid_to_date')
            ]),
         ]),
      ];
    }
 }`
