### ISSUE TITLE
Tabs missing on create form and default toolbar is missing on update form

### ISSUE THREAD

**Issue by m-lotze** [eminiarts/nova-tabs#222]
Laravel Nova v4.8.1
Nova Tabs v2.0.7

The tabs show up only on the update form and resource detail. On create form only panels are shown.

On resource detail the default toolbar shows, when using `withToolbar()`, but on the update form it is missing. Adding `withTitle()` will show only the resource title, not the default text `Update :resource: :title`.

**Comment by marcfilipan** [comment]
Try https://github.com/eminiarts/nova-tabs/releases/tag/2.0.8 and let me know if that solves it.

If not, please post your resource, as it works fine for me.

**Comment by m-lotze** [comment]
Tried 2.0.8 with this Resource:

```php
<?php
namespace App\Nova;

use App\Models\Country as CountryModel;
use Eminiarts\Tabs\Tab;
use Eminiarts\Tabs\Tabs;
use Eminiarts\Tabs\Traits\HasTabs;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

/** @mixin \App\Models\Country */
class Country extends Resource
{
    use HasTabs;

    /** @var string */
    public static $model = CountryModel::class;

    /** @var array */
    public static $orderBy = ['name' => 'asc'];

    /** @var array */
    public static $search = ['name'];

    /** @var string */
    public static $title = 'name';

    /** @var array */
    public static $with = ['regions'];

    public function fields(NovaRequest $request): array
    {
//        return [
//            Text::make('Name', 'name'),
//            Text::make('ISO 2 Code', 'iso_3166_2'),
//            Text::make('ISO 3 Code', 'iso_3166_3'),
//            Text::make('Auto-KZ', 'licence_plate_code'),
//            Text::make('Währungscode', 'iso_4217'),
//            Text::make('Währung', 'currency')
//        ];

        return [
            Tabs::make('Tabs', [
                Tab::make('Allgemein', [
                    Text::make('Name', 'name'),
                    Text::make('ISO 2 Code', 'iso_3166_2'),
                    Text::make('ISO 3 Code', 'iso_3166_3'),
                ]),
                Tab::make('Währung', [
                    Text::make('Auto-KZ', 'licence_plate_code'),
                    Text::make('Währungscode', 'iso_4217'),
                    Text::make('Währung', 'currency')
                ])
            ])->withToolbar()
        ];
    }

    public function filters(NovaRequest $request): array
    {
        return [];
    }

    public static function label(): string
    {
        return 'Länder';
    }

    public static function singularLabel(): string
    {
        return 'Land';
    }
}
```

Without tabs this is the resource form and detail:

![form-without-tabs](https://user-images.githubusercontent.com/7899692/173784916-5f293567-ee68-45e4-bc96-49c7dc9d7c93.PNG)

![detail-without-tabs](https://user-images.githubusercontent.com/7899692/173784943-2d396268-39cd-45c2-934c-ab7815dcb15d.PNG)

With tabs:

![form-with-tabs](https://user-images.githubusercontent.com/7899692/173785004-cf8af9a9-2f68-4e55-8620-41aae417676e.PNG)

![detail-with-tabs](https://user-images.githubusercontent.com/7899692/173785024-696a0c40-afe1-4b05-8c85-4c9a343a9cab.PNG)

I think `withToolbar()` on `Tabs` should show the default nova titles like in the first 2 screenshots.

The tabs not showing on the create form was my mistake. I used `Tabs::make($this->title(), ...`, which is empty on create and therefore no tabs were created. It works with `Tabs::make(self::label(), ...`

**Comment by marcfilipan** [comment]
You define the titles yourself, so you can simply do the following to accomplish that:
```
Tabs::make(__(':resource Details: :title', ['resource' => $resource->singularLabel(), 'title' => (string) $resource->title(),])
```

**Comment by garrettmassey1** [comment]
This still appears to be an issue with Nova 4 and tabs v2.2. 

When using the `fieldsForUpdate()` method on a resource, the `Tabs` field doesn't display the "name" / toolbar title even when calling the `withToolbar()` method.
