### ISSUE TITLE
Not showing actions

### ISSUE THREAD

**Issue by stonkeep** [eminiarts/nova-tabs#224]
In version 4.9.2 of Laravel Nova, it is not showing resource actions

**Comment by marcfilipan** [comment]
Could you post the code you have, a Screenshot of the result that goes wrong and a Screenshot of what you expected?

**Comment by Lednerb** [comment]
I can confirm the issue and provide the following screenshot:

![grafik](https://user-images.githubusercontent.com/2056876/174436955-90c0b036-6cec-42ad-9df3-4ef16c9d974f.png)

![grafik](https://user-images.githubusercontent.com/2056876/174436997-2282e327-53dd-404d-9ddb-3102e80bbca7.png)


Screenshot from relevant code pages of the `Client` resource:


![grafik](https://user-images.githubusercontent.com/2056876/174437083-6a2031ad-19ca-47a5-8239-242f3fcff07f.png)

also the `HasTabs` trait is imported:

```php
class Client extends Resource
{
    use HasTabs;
    ...
```

**Comment by marcfilipan** [comment]
Please call the showToolbar method on tabs

**Comment by Lednerb** [comment]
@marcfilipan thanks for your reply, but it seems that there is no such method:

![grafik](https://user-images.githubusercontent.com/2056876/174446940-cef566eb-2c77-4348-8d75-4c4c8fdf970d.png)

**Comment by marcfilipan** [comment]
Thanks for the update and sorry for the wrong method name, replied from phone and didn't actually look it up.
