### ISSUE TITLE
Dynamic tabs name

### ISSUE THREAD

**Issue by philipbaginski** [eminiarts/nova-tabs#225]
Hi!

Is it possible to make dynamic name for tabs?:

Tabs::make(__('Dynamic name'), [
                Tab::make(__('Tab 1'), [
                ...
                ],
                Tab::make(__('Tab 2'), [
                ...
                ],
            ]),

**Comment by marcfilipan** [comment]
What do you mean with dynamic name?

**Comment by philipbaginski** [comment]
Some data belongs to resource e.g. name of any info from resource table.

Is it possible now to fetch any data from resource table and use it as tabs name?

**Comment by philipbaginski** [comment]
The reason I'm asking: if you don't have tabs in this place will be shown current resource info. With tabs it is removed and there is fixed name of tags.

**Comment by marcfilipan** [comment]
You can adjust the panel name of Tabs to anything you wish though, if you want the regular resource name, you can simply do:
’’’
Tabs::make(__(':resource Details: :title', ['resource' => $this->singularLabel(), 'title' => (string) $this->title(),])
’’’

**Comment by philipbaginski** [comment]
Thank you. I have not seen it in the docs.
