### ISSUE TITLE
Tabs name not showing

### ISSUE THREAD

**Issue by aqjw** [eminiarts/nova-tabs#226]
Tabs name not showing without the `withToolbar` method.
Is there a way to show the tabs name without other actions on the right side?

<img width="1437" alt="Screenshot 2022-06-26 at 18 15 24" src="https://user-images.githubusercontent.com/13101908/175821059-f0cc6d20-7efb-40d0-88a9-4aded2f389c6.png">

**Comment by marcfilipan** [comment]
Please call the showTitle method on Tabs.
