### ISSUE TITLE
Query string is different since Nova 4

### ISSUE THREAD

**Issue by baszach** [eminiarts/nova-tabs#231]
Hi,

I updated this package to be compatible with Nova 4. I've noticed that the URL query string is quite different and more verbose than before.

Before: `tab=documents`
After: `__RESOURCE__: __TITLE__=__TAB_NAME__&__SECOND_TAB_NAME__=__OTHER__`

Is there a reason for that. Would be great to get some input on this :)

Thanks in advance

**Comment by marcfilipan** [comment]
Yes, the ability to have multiple tabs instances on a single resource.

**Comment by baszach** [comment]
Okay. I think I was able to have multiple tab instances before, though. Not sure :/
