### ISSUE TITLE
How to show content (Relationship Tabs) if it is collapsed on another page?

### ISSUE THREAD

**Issue by RuslanMak** [eminiarts/nova-tabs#233]
Use with collapsable-relations (https://nova.laravel.com/docs/4.0/releases.html#collapsable-relations)

If I turned off the resource on the one page I don’t see it on another page where I use Tabs
![1](https://user-images.githubusercontent.com/37831442/178369290-651d3ec4-8da3-472a-be44-0e814001d4c7.jpg)
![2](https://user-images.githubusercontent.com/37831442/178369307-f8b6aa19-0090-4d4b-bfd1-5843926c3fd3.jpg)

Thanks!

**Comment by marcfilipan** [comment]
Tabs aren't pages though. Nova Tabs simply collects the tabs you specify in a resource and their related fields, then simply hides the fields from the non-active tabs. 

It doesn't do much more than that. So it all depends on what you specify in a resource and tab instances.

**Comment by RuslanMak** [comment]
Here is my solution 

```
.tab-group .tab h1.items-center {
    display: flex;
    align-items: center;
    padding: 6px 16px 0;
    margin: 0;
}
```
