### ISSUE TITLE
Relation resource doesnt show if HasTabs is declared

### ISSUE THREAD

**Issue by francisacosta** [eminiarts/nova-tabs#234]
I was trying to Tabs some of my Relation resource. the relation resources are hidden if its not in tabs.

**Comment by marcfilipan** [comment]
@ackermann do you perhaps have time to look into the changes the latest nova version did, which causes relation tabs not to show up any longer?

Thought I'd be able to create some time this week to look into it, but unfortunately that's not possible for another two weeks.
 
Related issues are:
https://github.com/eminiarts/nova-tabs/issues/236
https://github.com/eminiarts/nova-tabs/issues/229

**Comment by mstaack** [comment]
@marcfilipan i tried going down that nova/trait/fetch panel rabbit hole to find the bug. but man i am lost.

did you have time to look into this?

cheers

**Comment by marcfilipan** [comment]
Fixed in https://github.com/eminiarts/nova-tabs/releases/tag/2.2.0
