### ISSUE TITLE
Pivot fields not shown

### ISSUE THREAD

**Issue by cserepesmark** [eminiarts/nova-tabs#236]
Using Tabs results in pivot tables not shown. My Percent column is not visible. It is also not included in the XHR request. The field method completely ignored.

```
use HasTabs;

Tabs::make('Related', [
    BelongsToMany::make('Products')
        ->fields(fn () => [
            Number::make('Percent')
        ]),
]),
```

If I do not use Tabs, my Percent field is shown in the Related table.

```
BelongsToMany::make('Products')
    ->fields(fn () => [
        Number::make('Percent')
    ]),
```

**Comment by marcfilipan** [comment]
Fixed in https://github.com/eminiarts/nova-tabs/releases/tag/2.2.0
