### ISSUE TITLE
Mixing fields with relations not working

### ISSUE THREAD

**Issue by flxsource** [eminiarts/nova-tabs#24]
Nova Tabs: 1.0.4
Nova: 1.3.1
Laravel: 5.7.7

Mixing fields and relations in a single tab (as mentioned in #7 ) appears to no longer work since 1.0.

Using the documented syntax breaks the relation into their own tab regardless of what else is in the defined tab, and using the `addTab` syntax detailed in #7 results in a `Only listable fields or Panel allowed.` error.

**Comment by bigperson** [comment]
i have some problem

**Comment by RVxLab** [comment]
Due to the age of this issue and my attempt to clean everything up I'm closing this. If this is still a problem for you, please re-open this or create a new one.
