### ISSUE TITLE
Impossible to use within Nova Actions

### ISSUE THREAD

**Issue by lazerg** [eminiarts/nova-tabs#241]
Hello. Your package is great. 

I have a big form in an action and I wanted to use Tabulation.

```php
class NovaActivateCompanyAction extends Action
{
    use InteractsWithQueue, Queueable;

    public function fields(NovaRequest $request): array
    {
        return [
            Tabs::make('Company details', [
                Tab::make('User details', [
                    // ...
                ]),

                Tab::make('Register form #1', [
                    // ...
                ]),
            ]),
        ];
    }
```

After having such action, I am getting this error: `Method Eminiarts\\Tabs\\Tabs::authorizedToSee does not exist.`

```json
{
    "message": "Method Eminiarts\\Tabs\\Tabs::authorizedToSee does not exist.",
    "exception": "BadMethodCallException",
    "file": "/var/www/app/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php",
    "line": 113,
}
```

**Comment by mstaack** [comment]
It's not supposed to be used insight nova actions. Tabs is for resources.

**Comment by lazerg** [comment]
> It's not supposed to be used insight nova actions. Tabs is for resources.

I know it 😃. But is there any hack to overcome this? Because I need it in actions.

If there is absolutely no way of it, let me know, i will close the issue.
