### ISSUE TITLE
Possibility to preserve tabs?

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [eminiarts/nova-tabs#244]
We have such tabs structure

```
Tabs::make('Tabs', [
                Tab::make('Tab 1', [
                    // Fields
                ]),
                HasMany::make('Tab 2'),
                Tab::make('Tab 3', [
                    // Fields
                ]),
                HasMany::make('Tab 4'),
                HasMany::make('Tab 5')
])->showTitle(),
```

When we click create/view/edit, for example, in tab 2, it opens the form, but the tabs are missing.
So I am wondering if it is possible to preserve them?

And a suggestion: Would be good to enable Discussions for this repo, so questions like these could be posted there :)

**Comment by marcfilipan** [comment]
HasMany doesn't show up on edit. That's due to Nova's design. 

I don't require it myself, but if you want to make a PR to make it optionally available, you're welcome to do so.
