### ISSUE TITLE
Nova-tabs theme switcher doesn't work after latest update (2.2.1)

### ISSUE THREAD

**Issue by kichetof** [eminiarts/nova-tabs#250]
Hello,

I updated nova-tabs to latest (2.2.1) and when I switch theme, it is not the right color displayed.

I recorded a small video to show you
![nova tab switch bug](https://i.ibb.co/DWZXcyC/nova-tabs-theme-bug.gif) 

Thank's for your great plugin!

**Comment by crynobone** [comment]
@kichetof You need to update `nova-kit/nova-packages-tool` to `1.3.2`, sorry for the inconvenience.

**Comment by kichetof** [comment]
@crynobone thanks for your feedback. I didn't realize that the switch was depending on another package.
Update 1.3.2 fix this issue! Thanks again!
