### ISSUE TITLE
Edit button on details view

### ISSUE THREAD

**Issue by ss-koshala** [eminiarts/nova-tabs#257]
Hello, I just want to know cant we use edit button on details view.?
![Screenshot (137)](https://user-images.githubusercontent.com/65384702/194811638-791b94e4-dad9-4dc6-a416-a3812d673adc.png)
 
Thanks.

**Comment by ArtDepartmentMJ** [comment]
You need to add withToolbar() to Tabs::make

https://github.com/eminiarts/nova-tabs/issues/224#issuecomment-1159463407
