### ISSUE TITLE
Can't delete images if using Tabs in a resource with TabsOnEdit

### ISSUE THREAD

**Issue by AliNetmatter** [eminiarts/nova-tabs#28]
When trying to delete an image the URL the delete call is made to does not include the correct resource id.

As an example, the call is made to
`/nova-api/products/undefined/field/image`
where `undefined` should be replaced with the resource ID.

**Comment by chatzisnik** [comment]
+1

**Comment by phucnguyenvn** [comment]
+1

**Comment by SadeghPM** [comment]
+1 and same issue

**Comment by preliot** [comment]
+1 Seems to go wrong in `Laravel\Nova\Http\Controllers\FieldDestroyController.php` on line 28

**Comment by DerekBuntin** [comment]
This issue is still happening to me, as soon as I removed TabsOnEdit the images deleted successfully.

**Comment by bernhardh** [comment]
Yes. Still an issue

**Comment by RVxLab** [comment]
I'll try to take a look at it this week.

**Comment by 949mac** [comment]
Thanks @RVxLab !

**Comment by Yann-BUTSCHER-EIRL** [comment]
Hello.
Do you have any updates on this ?

As much as we like your package, this kind of bugs makes us wonder if it would be easier to not use it.

Thanks anyway for all the work you've put in it.

**Comment by RVxLab** [comment]
Okay first of all, I'm sorry that I took this long to address this issue. Poor form on my part.

As for the issue, yes I found the problem and implemented a fix, see #59 and commit 55237f38750529a8daac16d8c37b125c91338d18.

I'm tagging 1.3.1 with this fix.

**Comment by amidesfahani** [comment]
+1 and same issue

**Comment by TomOudeRengerink** [comment]
Hey any updates on this? @RVxLab you mentioned it fixed in #59. Does not seems to work (anymore).
