### ISSUE TITLE
Resource detail toolbar disappears when all fields are inside tabs

### ISSUE THREAD

**Issue by ppisecky** [eminiarts/nova-tabs#3]
When you put all fields into tabs and navigate to the resource detail, then the toolbar doesn't get displayed. i.e. the actions button, edit button and delete buttons are not present. At least one field must be outside of tabs. Also that field cannot be inside a panel either as that also doesn't make the buttons display.

![tabs](https://user-images.githubusercontent.com/10659431/50383109-76938900-06ad-11e9-8f09-95d28b0d01c6.PNG)

![image](https://user-images.githubusercontent.com/10659431/50383106-6a0f3080-06ad-11e9-945b-3fd786d92ae7.png)

**Comment by bajramemini** [comment]
Hello @ppisecky 

Thanks for the Issue. Never used the Tabs without any default Nova Panel.

### Tabs Panel with Toolbar

If you are only using a TabsPanel without another default Panel, you can set the third argument `showToolbar` to `true`.

![image](https://user-images.githubusercontent.com/3426944/50448780-608efe00-0923-11e9-9d55-3dc3d8d896e1.png)


```php
// in app/Nova/Resource.php

use Eminiarts\Tabs\TabsPanel;

public function fields(Request $request)
    {
        return [
            new TabsPanel('Contact Details', [
                'Address'   => [
                    ID::make('Id', 'id')->rules('required'),
                    Text::make('Email', 'email')->sortable(),
                    Text::make('Phone', 'phone')->sortable(),
                ],
                'Relations' => [
                    BelongsTo::make('User'),
                    MorphTo::make('Contactable')->types([
                        Client::class,
                        Invoice::class,
                    ]),
                ],
            ], true), // Third argument is $showToolbar = true
        ];
    }
```

Let me know if you need any further help.

Regrads
Bajram
