### ISSUE TITLE
Default search needs more bottom padding

### ISSUE THREAD

**Issue by patricktsg** [eminiarts/nova-tabs#30]
It's fine on smaller screens but full iwdth on 23" monitor looks cut off when focused on search input. Also - the background could be light grey to make the search stand out a little.

If it's possible to change in the package could you point me to where and I will fork it

![Screen Shot 2019-03-29 at 17 13 46](https://user-images.githubusercontent.com/16956839/55250623-87244400-5246-11e9-8c9e-9a4cfe29130b.png)

**Comment by bajramemini** [comment]
Hello @patricktsg 

Is this still a problem?

Should be [here.](https://github.com/eminiarts/nova-tabs/blob/master/resources/js/components/DetailTabs.vue#L172-L180)

Regards

**Comment by bajramemini** [comment]
Feel free to reopen the issue, if this is still a problem.

**Comment by patricktsg** [comment]
That's great! Thanks!
