### ISSUE TITLE
License concerns

### ISSUE THREAD

**Issue by devfrey** [eminiarts/nova-tabs#32]
Hello,

I noticed this package has code from [dkulyk/nova-tabs](https://github.com/dkulyk/nova-tabs). I have some concerns regarding the license. Perhaps it should also be more prominently visible that this package was sort of built on top of [@dkulyk's](https://github.com/dkulyk) implementation.

What are your thoughts?

**Comment by enesemini** [comment]
Hello Jeffrey,

As you can clearly see in the initial commit by Inkyvisitor, he mentions, that it is a fork from eminiarts/nova-tabs.

https://github.com/dkulyk/nova-tabs/commit/cc4e584e990654f90c19a73d97808a4c82fc1bff#diff-04c6e90faac2675aa89e2176d2eec7d8R3

Have a nice day.
