### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by dillingham** [eminiarts/nova-tabs#33]
Any chance of a dropdown on mobile?

Im using the responsive theme
https://novapackages.com/packages/gregoriohc/laravel-nova-theme-responsive

and the tabs arent really usable

**Comment by asilverstein** [comment]
Was this implemented?

**Comment by C14r** [comment]
Any news on this issue?

**Comment by asilverstein** [comment]
I was able to slightly improve things by adding the following CSS to get the tabs to at least wrap to a second row:

```
.relationship-tabs-panel.card > .flex-row {
    flex-wrap: wrap;
}
```
