### ISSUE TITLE
Edit tab and form validation

### ISSUE THREAD

**Issue by lvdhoorn** [eminiarts/nova-tabs#35]
When you use the edittab option and the form validation fails it would be nice that you can see that there is an error on a field inside a tab.

**Comment by christophrumpel** [comment]
Just tried the package out and I really liked it. Good work! This was also an issue I found. When you have validation errors you don't see on which tabs they are. In my case, the user would need to search through 5 different tabs to find it. Is this something you already know of? Would you be open for PRs?

**Comment by idragon81** [comment]
+1

**Comment by orlyapps** [comment]
+1

**Comment by giancanuz** [comment]
here it is my 2 cents:
my workaround extends nova-scroll-top  package
- install from https://github.com/tanmuhittin/nova-scroll-top 

- then I created: resources/js/my-nova-scroll-to-error.js with the following content
https://pastebin.com/UQPZkUqM

- added it to webpack.mix.js :
mix.js('resources/js/my-nova-scroll-to-error.js', 'public/js')

- compiled with: npm run production

- in my ServiceProvider (app/Providers/AppServiceProvider.php) I've added the following into boot() method:
`

		Nova::serving(function (ServingNova $event) {
			if(config('nova-scroll-top.on_error')) {
				Nova::script('nova-scroll-to-error',  app_path(). '/../public/js/my-nova-scroll-to-error.js');
			}
		});

`

not the best but it suits my (few) needs.

**Comment by bajramemini** [comment]
Hello there

Should be fixed as of [1.0.5](https://github.com/eminiarts/nova-tabs/releases/tag/1.0.5).

It should look like this:
![image](https://user-images.githubusercontent.com/3426944/61807205-5b524d00-ae39-11e9-8e3b-a560c7f368f5.png)

**Comment by lvdhoorn** [comment]
Thank you so much for this fix!
