### ISSUE TITLE
Feature: display all fields for MorphTo relations

### ISSUE THREAD

**Issue by 4n70w4** [eminiarts/nova-tabs#37]
Very useful display all fields for MorphTo relations instead link to resource.

Current:
![image](https://user-images.githubusercontent.com/38257723/57184849-a27c1200-6eca-11e9-9e11-6276bd89911d.png)

Expected:

![image](https://user-images.githubusercontent.com/38257723/57184870-e111cc80-6eca-11e9-8037-79ce4245b7c7.png)

**Comment by bajramemini** [comment]
Hey @4n70w4 

Not sure this has anything to do with the Tabs package. If you want a different MorphTo Field, that should be its own package. Couldn't find one on novapackages.com but maybe someone built something like this already.

If you have any further questions, please let me know or feel free to reopen the issue.

Regards
