### ISSUE TITLE
How to show more than 5 Resources on one Index Page?

### ISSUE THREAD

**Issue by dajoeberlei** [eminiarts/nova-tabs#39]
Hi, Is it possible to allow one Tab with Relations showing more than 5 Resources per Page?

Im working on a project where i almost always have between 5-10 Resources and i'd like to have them on the same page.

**Comment by RVxLab** [comment]
First off, sorry for the silence. This is a pretty nice idea, I'll take a look if this can be implemented.

**Comment by dajoeberlei** [comment]
@RVxLab no worries. I havent checked it out yet in your package but i know now that Nova has this variable build in for defining how many relationship model should be displayed. 
If you put this on the relation ship model:

`public static $perPageViaRelationship`

(its default is 5)

Like i said. Havent tried it on your package but maybe that already does the trick? :-)

**Comment by RVxLab** [comment]
If that does the trick do let me know and I’ll add it to the readme.
