### ISSUE TITLE
Multiple relationships in one tab?

### ISSUE THREAD

**Issue by 4n70w4** [eminiarts/nova-tabs#40]
I want to show several resources in one tab. I can not understand how this can be done.

![image](https://user-images.githubusercontent.com/38257723/59099942-42471880-892d-11e9-9c53-a526e6d2d432.png)

I wrapped it in a panel, but is created separate tab for each relation.

**Comment by hsharghi** [comment]
According to document in README file, it should be possible
There are two relations, `BlongsTo` and `MorphTo` in one tab named 'Relations', but I can't get the same result.

![Multiple relations in one tab](https://user-images.githubusercontent.com/2873823/62377800-b5998f00-b558-11e9-803b-5f5549448ddf.png)

**Comment by shazibrazzaq** [comment]
hey guys i am getting the same problem any solution?

**Comment by RVxLab** [comment]
HasMany, BelongsToMany, MorphMany, etc relationships don't render in tabs, they **are** the tabs. BelongsTo and HasOne should work just fine though.
