### ISSUE TITLE
Remember current tab

### ISSUE THREAD

**Issue by atmediauk** [eminiarts/nova-tabs#42]
Hello,

Is it possible to remember the current tab when editing a resource. When clicking "Update & Continue Editing" it always goes back to the first tab which would be frustrating for users.

**Comment by bolechen** [comment]
+1

**Comment by LorenzoSapora** [comment]
This is a duplicate of #27

Close and merge into that issue?

**Comment by bernhardh** [comment]
With my pull request https://github.com/eminiarts/nova-tabs/pull/86 this should be fixed

**Comment by RVxLab** [comment]
This is a duplicate of #27 and PR #86 should fix this. Any additional comments should be put in those.
