### ISSUE TITLE
all fields disappeared 

### ISSUE THREAD

**Issue by yassir3wad** [eminiarts/nova-tabs#44]
After upgrading nova to 2.0.9, all form fields have disappeared.
When I tried to unuse 'TabsOnEdit' trait, all fields appeared.

laravel: 7.8.30
nova: 2.0.9
nova-tabs: 1.0.5

**Comment by ArmeniaH** [comment]
Checkout https://github.com/eminiarts/nova-tabs/issues/43

**Comment by phlisg** [comment]
Not sure it's related to #43 

I have a similar issue: editing an existing record works fine with tabs, yet when I want to create a new one I have no fields, just the two buttons "create & add another" / "create record".

Upon clicking on "create record", I have this JS error:

```javascript
TypeError: Cannot read property 'status' of undefined
    at p.<anonymous> (app.js?id=af7f60e144c36d0eb627:1)
    at y (app.js?id=af7f60e144c36d0eb627:1)
    at Generator._invoke (app.js?id=af7f60e144c36d0eb627:1)
    at Generator.e.<computed> [as next] (app.js?id=af7f60e144c36d0eb627:1)
    at o (app.js?id=af7f60e144c36d0eb627:1)
    at app.js?id=af7f60e144c36d0eb627:1
    at new Promise (<anonymous>)
    at new t (app.js?id=af7f60e144c36d0eb627:1)
    at p.<anonymous> (app.js?id=af7f60e144c36d0eb627:1)
    at p.<anonymous> (app.js?id=af7f60e144c36d0eb627:1)
It @ vendor.js?id=eaffe66c3a2800ae7df2:1
jt @ vendor.js?id=eaffe66c3a2800ae7df2:1
Yt @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
Promise.catch (async)
Pt @ vendor.js?id=eaffe66c3a2800ae7df2:1
n @ vendor.js?id=eaffe66c3a2800ae7df2:1
Zo.i._wrapper @ vendor.js?id=eaffe66c3a2800ae7df2:1
```

Commenting out the `Trait` call re-enables resource creation.

**Comment by alanpilloud** [comment]
Same here, the issue is only present on resource creation.

**Comment by yassir3wad** [comment]
there is no error in the js console

**Comment by yassir3wad** [comment]
> Checkout #43

thanks
