### ISSUE TITLE
BUG Tabs only render on edit

### ISSUE THREAD

**Issue by happyDemon** [eminiarts/nova-tabs#45]
Using Nova 2.0.9 or 2.0.8 & the latest version of nova-tabs (with the tabsOnEdit fix).

When I try to created a resource I get a blank page (only the action buttons), with no error in my console.

When I try to view a resource I get `TypeError: Cannot set property 'fields' of undefined` error

The edit view is working perfectly though

Last working setup:
nova 2.0.7 + nova-tabs 1.0.4

**Comment by iamburny** [comment]
Yep, I had the same issue.

I fixed it by editing "src/TabsOnEdit.php" from

`
    protected function assignToPanels($label, Collection $panels)
    {
        return $panels->map(function ($field) use ($label) {
            // Disable default Panel, because it's not needed for Tabs
            // if (!$field->panel) {
            //     $field->panel = $label;
            // }
            return $field;
        });
    }
`
To

`
protected function assignToPanels($label, Collection $panels)
    {
        return $panels->map(function ($field) use ($label) {
            // Disable default Panel, because it's not needed for Tabs

            if ( !is_array($field) && !$field->panel ) {
                 $field->panel = $label;
                 dump($field->panel);
            }

            return $field;
        });
    }
`

**Comment by XternalSoft** [comment]
Thanks @iamburny, but for me, it's not resolved with your fix

**Comment by funkdoobiest** [comment]
Made a PR to fix this issue: https://github.com/eminiarts/nova-tabs/pull/46

**Comment by geraintp** [comment]
The PR fixed it for me on +1

Laravel 5.8
Nova 2.0.10
Tabs 1.0.5

**Comment by geraintp** [comment]
@iamburny 's fix solved it for me on 2.0.10
