### ISSUE TITLE
Styling problems with latest Nova

### ISSUE THREAD

**Issue by d8vjork** [eminiarts/nova-tabs#47]
![image](https://user-images.githubusercontent.com/2331052/63386238-7b265380-c39a-11e9-8497-46c92f4432f1.png)

**Comment by sirikkoster** [comment]
Add classes "relative h-9 flex-no-shrink mb-6 items-center" to "Attach Industry" container div wil fix this problem but I'm not familiar with Vue so I can't fix this yet ;)

**Comment by d8vjork** [comment]
@sirikkoster Yes, that can be a possible solution, the thing is that the package is doing something weird around it, I don't like the way Nova and most of the packages are developed on the frontend side

Anyway, thanks for the workaround 👍

**Comment by sirikkoster** [comment]
Is there any update on this?

**Comment by phuclh** [comment]
Any update on this? Seems just override the padding-bottom of class `mb-6`
