### ISSUE TITLE
Argument 1 passed to Laravel\Nova\Resource::removeNonCreationFields() must be an instance of Laravel\Nova\Http\Requests\NovaRequest

### ISSUE THREAD

**Issue by phuclh** [eminiarts/nova-tabs#48]
I got this error when using Nova 2.10 and nova-tabs v.1.0.6

`Argument 1 passed to Laravel\Nova\Resource::removeNonCreationFields() must be an instance of Laravel\Nova\Http\Requests\NovaRequest, instance of Laravel\Nova\Fields\FieldCollection given, called in /path/vendor/eminiarts/nova-tabs/src/TabsOnEdit.php on line 22`

**Comment by rikless** [comment]
it's on nova 2.1.0. Have it too

**Comment by ArmeniaH** [comment]
```'fields'    => $this->removeNonCreationFields($request, $this->resolveFields($request)),```

```'fields'    => $this->removeNonUpdateFields($request, $this->resolveFields($request)),```

```$request``` should be added as first parameter for ```removeNonCreationFields``` and ```removeNonUpdateFields```

**Comment by johanvanhelden** [comment]
I've created a PR, hopefully it gets merged :crossed_fingers:
