### ISSUE TITLE
keep tabs on edit view

### ISSUE THREAD

**Issue by simonfunk** [eminiarts/nova-tabs#5]
Hi

Thanks for your work!

Can you make that the tabs keep displaying on edit view? Now it's beautiful tabbed on detail view but on edit, it's all listed.

Would be great!

**Comment by JapSeyz** [comment]
For ideas on how to achieve it, the other Nova Tabs package has achieved it:
https://github.com/arsenaltech/nova-tab

I'll have a go at it in the weekend, if I get the time.

**Comment by PhilippeDirx** [comment]
Any update on this?
Would be really nice to have!

**Comment by simonfunk** [comment]
Thanks you very much!!
