### ISSUE TITLE
Add visibility to tabs based on condition?

### ISSUE THREAD

**Issue by scaventum** [eminiarts/nova-tabs#58]
Can we add condition per tab which can be hidden/shown based on condition e.g. user  role?

**Comment by newtongamajr** [comment]
Put your tabs array into a protected or private method and populate this array depending on which Tabs you wanna show. It works fine for me!

**Comment by marianne-fullstack** [comment]
Hi @newtongamajr do you have any sample code? Thanks!

**Comment by RVxLab** [comment]
Hmm, I quite like this idea actually. This could be done with a `when` method similar to the query builder.

I'll try to take a look this week or if someone wants to take a crack at it and make a PR please feel free to do so.

**Comment by RVxLab** [comment]
This has been implemented with the new `Tab` object (see `showIf` and `showUnless`). It's available in the master branch and will be released with 1.4.0.
