### ISSUE TITLE
Resources title is not display above the form detail

### ISSUE THREAD

**Issue by ronnytorresmtz** [eminiarts/nova-tabs#60]
Hi,
I have this code but the resources title is not display at the top of the page, do you know why?

This is my code. I appreciate any help.

      public function fields(Request $request)
      {
        $options = [];

        $options = [
            'Pending' => 'Pending',
            'Assigned' => 'Assigned',
            'Expired' => 'Expired',
            'Cancelled' => 'Cancelled',
        ];

        return [

            (new Tabs(__('Load Order Details'), [

                new Panel(__('General'),[

                    ID::make()->sortable(),

                    Text::make(__('Load Order')),

                    Text::make(__('From')),

                    Text::make(__('To')),

                    DateTime::make(__('PickUp Date')),

                    Text::make(__('Expires In'))->resolveUsing(function($date) {
                        $expireDate = Carbon::parse(date($date));
                        $format = Carbon::ONE_DAY_WORDS;
                        return $expireDate->diffForHumans(now(), ['options' => $format]);
                    })
                        ->hideWhenCreating()
                        ->hideWhenUpdating()
                        ->sortable(),

                    DateTime::make(__('Expires Date'), 'expires_in')
                        ->hideFromIndex()
                        ->format('ddd, MMM Do YYYY - h:mm a')
                        ->rules('required')
                        ->sortable(),
                    
                    
                    Select::make(__('Status'))
                        ->options($options),

                    Boolean::make(__('Active')),

                ]),
            
                new Panel(__('Weight and Pieces'),[
            
                    Number::make(__('Weight'))
                        ->hideFromIndex()
                        ->required(),
                    
                    Text::make(__('Unit Of Measure'))
                        ->hideFromIndex()
                        ->required(),
                    
                    Number::make(__('Pieces'))
                        ->hideFromIndex()
                        ->required(),
                ]),

                new Panel(__('Package Information'),[

                    Select::make(__('Package Type'))
                        ->hideFromIndex()
                        ->required()
                        ->options([
                            'No Package' => 'No Package',
                            'Box' => 'Box',
                            'Container' => 'Container'
                        ]),
                    
                    Number::make(__('Package Width'))
                        ->hideFromIndex()
                        ->required(),
                    
                    Number::make(__('Package Length'))
                        ->hideFromIndex()
                        ->required(),

                    Number::make(__('Package Height'))
                        ->hideFromIndex()
                        ->required(),
                ]),

                new Panel(__('Comments'),[

                    Textarea::make(__('Description of Items to Pickup'), 'desc_items_pickup')
                        ->alwaysShow()
                        ->rows(8)
                        ->hideFromIndex()
                        ->required(),
                    
                    Textarea::make(__('Observations'))
                        ->alwaysShow()
                        ->rows(8)
                        ->hideFromIndex()
                        ->required(),

                    // $table->integer('dispatcher_id');
                    // $table->integer('user_id');
                ]),

            ])),
        ];
    }

**Comment by jhae-de** [comment]
You need to set `withToolbar` to `true`.
See: https://github.com/eminiarts/nova-tabs#tabs-with-toolbar
