### ISSUE TITLE
Relationships in Edit View

### ISSUE THREAD

**Issue by iamoat** [eminiarts/nova-tabs#61]
Is it possible to include relationships in tabs on EditView? 

From nova documents it seems like relationships will be shown only in Detail View but not Create/Update view.

**Comment by bajramemini** [comment]
Hello @iamoat 

This doesn't have to do anything with the Tabs package if the Relationship doesn't have a create/update view. 

Feel free to reopen if I misunderstood your question.

**Comment by iamoat** [comment]
@bajramemini 
 
This is what I meant. 

First Pic. DetailView with Tabs "Extensions", "Queues", "Sip Trunks" in the bottom. 

![image](https://user-images.githubusercontent.com/1286835/68931854-f9409d80-07c3-11ea-8e20-d5e15febc67e.png)

Second Pic. When I clicked Edit the Tabs for those mentioned above were gone. 

![image](https://user-images.githubusercontent.com/1286835/68931934-27be7880-07c4-11ea-8aae-701e9220f78e.png)

**Comment by iamoat** [comment]
Nova: v2.6.1
Laravel: 5.8.35

**Comment by RVxLab** [comment]
@iamoat *slightly* belated on this.

Am I correct that those are `HasMany` relations? If so then what you're seeing it correct. `HasMany` fields don't display in forms.
