### ISSUE TITLE
not work in nova v2.7.0

### ISSUE THREAD

**Issue by loveyuxiao** [eminiarts/nova-tabs#62]
not work in nova v2.7.0

**Comment by loveyuxiao** [comment]
Argument 2 passed to App\Nova\ResourceUser::assignToPanels() must be an instance of Laravel\Nova\Fields\FieldCollection, instance of Illuminate\Support\Collection given, called in /home/ad/www/laravel6/vendor/laravel/nova/src/ResolvesFields.php on line 197

**Comment by rikless** [comment]
PR is sent. @bajramemini able to try, merge and tag please ?
https://github.com/eminiarts/nova-tabs/pull/63

**Comment by kosmonowt** [comment]
oops. 12 minutes to late. here as well:
#64

**Comment by rikless** [comment]
@kosmonowt https://github.com/eminiarts/nova-tabs/pull/64#issuecomment-553361488

**Comment by sohaibafifi** [comment]
Not working on relations for me. They are displayed at the bottom.

**Comment by rikless** [comment]
@sohaibafifi Right. Don't know why at this point. Seems related to nova.

**Comment by rikless** [comment]
So, when a tab contains a HasMany type, it breaks the expected behavior. Any idea @bajramemini ?

**Comment by bajramemini** [comment]
Hello everyone

Had a lot to do last week, will try to get this fixed this week. Not sure what is causing the problem yet. If anyone has an idea, please let me know.

**Comment by rikless** [comment]
@bajramemini it's a nova related issue. It will be patched in Nova 2.7.2 or 2.8.0, you don't have to do anything.

**Comment by rikless** [comment]
Confirmed, fixed in nova 2.8

**Comment by bajramemini** [comment]
Awesome, thanks @rikless
