### ISSUE TITLE
Doesn't have support for nova 2.7.0

### ISSUE THREAD

**Issue by binaryk** [eminiarts/nova-tabs#69]
Tabs aren't loaded for the latest nova release.

**Comment by binaryk** [comment]
The component is visible in the vue dev tools, but it doesn't render tabs. 
![image](https://user-images.githubusercontent.com/6833714/68771542-e77ac100-0630-11ea-9a8d-b0f1e2fa9de0.png)

**Comment by rikless** [comment]
See #62 
It looks related to HasMany fields.

**Comment by namixmedia** [comment]
Also having this problem. HasMany fields are not shown in new tab.

**Comment by newtongamajr** [comment]
Also the same situation, I'm passing thru...

**Comment by klepak** [comment]
Same issue, looks like problems with relationship fields in general. 
If I only have Text fields in the Tab panel, it works, but as soon as I add a relationship field, the whole Tab panel disappears, and is replaced with only the relationship field as if I had only used that directly.

**Comment by binaryk** [comment]
That's a big blocker, we basically cannot update the nova package.

**Comment by rikless** [comment]
This package has the exactly same issue : https://github.com/dkulyk/nova-tabs

**Comment by binaryk** [comment]
Then it seems that they modified something in nova itself. I tried to debug, but it's too verbose :)

**Comment by ralphschindler** [comment]
I've found the issue in nova, I will reach out on the issue tracker and report what I've found, its def. an issue with merging metadata (thus, `listable` is being sent as `true` instead of `false` which forces a relationship panel to be created instead of a panel within a tab.

**Comment by rikless** [comment]
fixed in nova 2.8

**Comment by piotrgulbis** [comment]
> fixed in nova 2.8

Confirmed working in nova 2.8
