### ISSUE TITLE
Mix fields with relations

### ISSUE THREAD

**Issue by JapSeyz** [eminiarts/nova-tabs#7]
Hey,

I can't figure out out to create a tab-panel with tabs for both regular fields and relations, eg:

| Details | Meta | Cars (Relation) | Driver ( Relation |

I can create one panel via new TabsPanel with regular fields, and relationships via Tabs::make, but if I try to add one to the either, it fails.

Is there a smart way to add the relationship tabs to the TabsPanel?

Cheers,

**Comment by bajramemini** [comment]
Hello @JapSeyz 

This is not possible yet. I didn't need a mixed Tab and Fields yet but this is definitely something I'd like to implement.

Will have to think about how to implement it but I'll let you know when I have a solution.

Regards,

**Comment by JapSeyz** [comment]
I'll see if I can get a PR made for it

**Comment by JapSeyz** [comment]
I have a working copy now, but it requires a little bit of a hack, because of the way Laravel handles Panels

**Comment by JapSeyz** [comment]
Couldn't come up with a good solution.

Nova does a lot of mumbo-jumbo with the panels:

1) All fields must have a panel, if the panel attribute is undefined, the JS crashes.
2) If Nova sees a relationship inside a panel, it takes it out and displays it as its own panel.
3) Nova doesn't guarantee the order of the panels - I created a hidden panel where Nova could put fields it duplicated from Tabs because it's not technically a Panel, but there's no way to guarantee that the action buttons stay at the top of the page.

I got to where it works with Fields & Relations together, but the Action bar remains missing.

![capture](https://user-images.githubusercontent.com/2234034/50870357-fe6cd900-13b7-11e9-9fad-92a8ce0a14c6.PNG)
![capture 2png](https://user-images.githubusercontent.com/2234034/50870358-ff056f80-13b7-11e9-92a2-2fde58f5587a.PNG)

**Comment by bajramemini** [comment]
Some crazy stuff going on in Nova, haha.

I managed to get the Tabs working like this:

![image](https://user-images.githubusercontent.com/3426944/50980965-2a907300-14fa-11e9-944a-1909b82e4786.png)

However, I don't like that it is a "Field" and not a Panel. I didn't find a good way to show the default toolbar or actions/buttons.

I tried it with a custom Panel component but it ended up ugly and broke everything, that's why I rerverted it back to this working point. Not really sure how to go from here, will try it again in a couple of hours, maybe I can get it to work.

Regards

**Comment by bajramemini** [comment]
Hello @JapSeyz 

Finally, I got it working.

![image](https://user-images.githubusercontent.com/3426944/50997426-cfc04100-1524-11e9-9f66-7a2bd626ffaf.png)

With this markup, it is possible to wrap tabs and show the toolbar:

```php
use Eminiarts\Tabs\Tabs;
use Eminiarts\Tabs\TabsPanel;

public function fields(Request $request)
{
    return [
        (new TabsPanel(__('Client Custom Details'), [
            Tabs::make()
                ->addTab(__('Details'), [
                    ID::make('Id', 'id')->rules('required')->hideFromIndex(),
                    Text::make('Name', 'name'),
                ])
                ->addTab(__('Invoices'), HasMany::make('Invoices'))
            ,
        ]))->withToolbar(),
    ];
}
```


If you don't need the Toolbar and want to combine Fields with Relation, you can use:
```php
use Eminiarts\Tabs\Tabs;
use Eminiarts\Tabs\TabsPanel;

public function fields(Request $request)
{
    return [
       
           Tabs::make()
                ->addTab(__('Details'), [
                    ID::make('Id', 'id')->rules('required')->hideFromIndex(),
                    Text::make('Name', 'name'),
                ])
                ->addTab(__('Invoices'), HasMany::make('Invoices'))
            ,
       
    ];
}
```

It is not tagged yet.

Somehow, it combines more than needed.

![image](https://user-images.githubusercontent.com/3426944/50997383-b15a4580-1524-11e9-9138-657542c7bd3a.png)

Which is not intended. Fill have to fix this, then I can release it.

Regards

**Comment by JapSeyz** [comment]
Sweet! It looks promising

**Comment by bajramemini** [comment]
Tagged as [0.3.0](https://github.com/eminiarts/nova-tabs/releases/tag/0.3.0)

Let me know if you have further issues.

**Comment by JapSeyz** [comment]
@bajramemini There's a small issue with it in ResolvesFields, since it no longer respects ->hideFromDetail(), as the $field in the call resolves to the Tab, ignoring every field inside of the Tab

**Comment by bajramemini** [comment]
Ok thanks. Will solve it asap.

**Comment by JapSeyz** [comment]
Found another issue, not sure why this happens, the only difference I can find is that it works in Car.php but not CarSeat.php, so the compound name, otherwise the two files are identical.

![annotation 2019-01-15 001543](https://user-images.githubusercontent.com/2234034/51147536-d61f2780-185a-11e9-9efc-0ee2b9397dcd.jpg)

TabsPanel has undefined group names, which results in:

```javascript
[Vue warn]: Unknown custom element: <detail-undefined> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <DetailTabs> at resources/js/components/Tabs.vue
       <TabsPanel> at resources/js/components/TabsPanel.vue
         <LoadingView> at resources/js/components/LoadingView.vue
           <Detail> at resources/js/views/Detail.vue
             <Root>
```


The code for that is:

```php
(new TabsPanel(__('List name'), [
          Tabs::make()
              ->addTab(__('Details'), [
                  Text::make('Title', 'title'),
              ])
              ->addTab(__('v'), HasMany::make('Values', 'values', ListValue::class)),
        ]))->withToolbar(),
```

**Comment by bajramemini** [comment]
Opened two separate issues. Worked on the first one yesterday, but I am still not finish yet. Will keep you updated on the issues.

Going to close this one.
