### ISSUE TITLE
HasMany relation stopped working

### ISSUE THREAD

**Issue by vbezruchkin** [eminiarts/nova-tabs#70]
Hi,

The latest version of the package does not display HasMany relations as separate tabs anymore. 
So when you mix tabs & models based on HasMany type relations, each one had own tab. This does not work anymore.

Please fix. Thanks in advance.

**Comment by akeresztesi** [comment]
Which version of Nova are you using?
Maybe related to #69

**Comment by vbezruchkin** [comment]
I use the latest version of Nova which is 2.9.0 now, and I can confirm the problem still exists. Thanks

**Comment by vbezruchkin** [comment]
Please ignore. Working fine now. Cheers.

**Comment by ziming** [comment]
mine wasn't working in the latest version
