### ISSUE TITLE
Tabs do not scroll on edit view

### ISSUE THREAD

**Issue by iMuMz** [eminiarts/nova-tabs#71]
Laravel Nova : 2.8.0
Tabs : 1.0

The tabs do not scroll on edit view when there are a lot of tabs on the resource. The tabs scroll correctly only when you view a resource.

<img width="1146" alt="Screenshot 2019-12-06 at 10 23 04" src="https://user-images.githubusercontent.com/22936672/70308041-1d1b6000-1813-11ea-982d-0adbcdcf5f98.png">

**Comment by CitizenBeta** [comment]
I'm also running into this on 3.x. Would be great if the tab layout matched the detail view. <3

**Comment by RVxLab** [comment]
Can you give this a go with the latest version?

**Comment by Marianne00** [comment]
+1 pls

**Comment by Marianne00** [comment]
it's just a simple overflow-x-auto, guys

![image](https://user-images.githubusercontent.com/21253453/101815704-e4674280-3b5a-11eb-8fc4-86f67c497024.png)

**Comment by RVxLab** [comment]
@Marianne00 I'm taking some time this weekend to look at this. If it's this simple then I'll take it along.

**Comment by Marianne00** [comment]
Hi guys! Any updates on this?

**Comment by RVxLab** [comment]
Unfortunately I didn't find the time to look at this, as well as being busy with a major update. I do plan to rework the UI components quite a bit.

If you want to submit a PR for this, please feel free to do so.
