### ISSUE TITLE
use TabsOnEdit;  errors in nova 2.9.2 

### ISSUE THREAD

**Issue by MilesWuCode** [eminiarts/nova-tabs#75]
Best Plugin!!!

v1.2.1

When form
Argument 1 passed to Laravel\Nova\Resource::removeNonCreationFields() must be an instance of Laravel\Nova\Http\Requests\NovaRequest, instance of Laravel\Nova\Fields\FieldCollection given, called in vendor/eminiarts/nova-tabs/src/TabsOnEdit.php on line 23

**Comment by dkulyk** [comment]
This is has broken in https://github.com/eminiarts/nova-tabs/pull/74/files#diff-41ad8b03bba6a360c6b7c5910ab3f2f8L22

**Comment by kosmonowt** [comment]
also here! please fix!

**Comment by rikless** [comment]
Got the issue too :/

**Comment by alexsaab** [comment]
I got error too

**Comment by ronnytorresmtz** [comment]
I have the same issue

**Comment by bajramemini** [comment]
Hey everyone

As I have a lot to do the next few days, I would appreciate a PR for this. Otherwise, I'll take a look at it within a week.

Regards

**Comment by LorenzoSapora** [comment]
@bajramemini here's the PR https://github.com/eminiarts/nova-tabs/pull/76
