### ISSUE TITLE
Warning: Declaration of Eminiarts\Tabs\TabsOnEdit::assignToPanels ... should be compatible with

### ISSUE THREAD

**Issue by preliot** [eminiarts/nova-tabs#78]
Just updated all packages to most recent one and got this error:

`Declaration of Eminiarts\Tabs\TabsOnEdit::assignToPanels($label, Laravel\Nova\Fields\FieldCollection $fields) should be compatible with Laravel\Nova\Resource::assignToPanels($label, Illuminate\Support\Collection $panels)`

Temp fix:

/nova-tabs/src/TabsOnEdit.php

use Illuminate\Support\Collection as FieldCollection;

**Comment by pbrisson** [comment]
@preliot Can you give additional details regarding your versions?

Current release of Nova is 2.9.2 and Nova Tabs is 1.2.2; Can't reproduce the error.

The current definition of assignToPanels function doesn't match what you report neither:

```
    /**
     * Assign the fields with the given panels to their parent panel.
     *
     * @param  string  $label
     * @param  \Laravel\Nova\Fields\FieldCollection  $fields
     * @return \Laravel\Nova\Fields\FieldCollection
     */
    protected function assignToPanels($label, FieldCollection $fields)
    {
        return $fields->map(function ($field) use ($label) {
            if (! $field->panel) {
                $field->panel = $label;
            }

            return $field;
        });
    }
```

Looks like you're still using Nova 2.9.0. Look at nova/src/ResolveFields.php line #572 to #588 to make sure. Definition should be identical as the one above.

**Comment by preliot** [comment]
Updated nova to 2.11.1 and issue is no longer present! Issue was due to old nova install, which was not updated with composer update (needed to manually update nova).

@pbrisson Sorry, took to long. Was occupied with other work.
