### ISSUE TITLE
Fields unstyled when using 'Content' as tab title

### ISSUE THREAD

**Issue by LorenzoSapora** [eminiarts/nova-tabs#80]
Package: 1.2.2
Nova: 2.9.2
Laravel: 5.8.*
---

When you call a tab "Content", it causes issues with styling of that tabs fields.

```php
 public function fields(Request $request)
    {
        return [
            (new Tabs($this->title, [
                'Content'  => [
                    DateTime::make('Created at')
                        ->hideFromIndex(),
                ],
            ]))
                ->withToolbar()
                ->defaultSearch(true),
        ];
```
![image](https://user-images.githubusercontent.com/25519274/71264029-19bbc480-233b-11ea-931f-d3fb1c57680f.png)

Changing it to "Contentt"

```php
 public function fields(Request $request)
    {
        return [
            (new Tabs($this->title, [
                'Contentt'  => [
                    DateTime::make('Created at')
                        ->hideFromIndex(),
                ],
            ]))
                ->withToolbar()
                ->defaultSearch(true),
        ];
```

![image](https://user-images.githubusercontent.com/25519274/71264109-42dc5500-233b-11ea-95bb-651de291b64d.png)

(ignore the created at duplication in the screenshots, I was testing if it was the field itself)

**Comment by RVxLab** [comment]
Is this still an issue with the latest version of Nova?

**Comment by RVxLab** [comment]
Doesn't seem to be an issue in Nova 3.x.
