### ISSUE TITLE
Overflowing content is cut off

### ISSUE THREAD

**Issue by swatty007** [eminiarts/nova-tabs#81]
If you have too large content on the relationship tabs it gets cut off by the overflow-hidden class.
This is problematic if you have content, which should actually render over the boundaries like custom select fields.

![grafik](https://user-images.githubusercontent.com/38767638/71477095-72caa300-27e8-11ea-8bdf-f0af6b68c0df.png)

Not sure if the overflow-hidden is needed there, but it would be nice to have an option to disable it, when needed.

**Comment by ntsbstn** [comment]
I'm using whitecube/nova-flexible-content and I confirm, this is annoying.

<img width="445" alt="Screenshot 2020-06-26 at 10 06 31" src="https://user-images.githubusercontent.com/23659828/85835210-edbf4700-b794-11ea-83d1-291eb7977b4c.png">
