### ISSUE TITLE
Respect Panels and Panel order on edit page

### ISSUE THREAD

**Issue by BenjaminBrandtner** [eminiarts/nova-tabs#85]
On my User Resource I use one Tabs-Component and one standard Nova Panel, like this:

```
    public function fields(Request $request)
    {
        return [
            new Tabs(__('Personal Details'), $this->getPersonalDetailsFields($request)),
            new Panel(__('Game Details'), $this->getGameDetailsFields($request)),
        ];
    }
```

On the detail page, two cards are displayed, with the Personal Details at the top and the Game Details at the bottom, as expected.

On the edit page however, just one card is displayed, with the Game Details at the top, then the tab bar, then the Personal Details fields.  
It looks like [this screenshot](https://user-images.githubusercontent.com/3426944/52180482-13862d80-27e7-11e9-9193-58c5801322b0.png) from potentially related issue #14.

My desired behaviour is for the edit page to look exactly like the detail page, one card for the Tab-component, one card for the Panel-component, in the same order that they are declared in the source code. Is this possible?

**Comment by medvinator** [comment]
This is because method **updateFields** in trait **TabsOnEdit** return only one field in **FieldCollection**

```php
    /**
     * Resolve the update fields.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return \Laravel\Nova\Fields\FieldCollection
     */
    public function updateFields(NovaRequest $request)
    {
        return new FieldCollection(
            [
                'Tabs' => [
                    'component' => 'tabs',
                    'fields'    => $this->removeNonUpdateFields($request, $this->resolveFields($request)),
                    'panel'     => Panel::defaultNameForUpdate($request->newResource()),
                ],
            ]
        );
    }
```

**Comment by RVxLab** [comment]
I'd need to take a look how this could be implemented correctly. Due to limited time that might be a while. If you want to take a crack at it yourself please feel free to do so.

**Comment by elijahworkz** [comment]
I added a pull request that solves this issue. #139
