### ISSUE TITLE
Can't create or edit with relationships

### ISSUE THREAD

**Issue by raulsh** [eminiarts/nova-tabs#89]
Tabs works great even with relationships but can't edit or create with those. I tried another packages but it wasn't enough.

**Comment by raulsh** [comment]
Related to #61 but issue was closed.

**Comment by RVxLab** [comment]
Hi Raulsh,

What kind of relationships are they? `BelongsTo` fields should appear as you'd expect, but `HasMany` or `BelongsToMany` don't as they don't show up in Nova's forms.

**Comment by RVxLab** [comment]
Due to the age of this issue I'm closing it. If my above comment isn't related to this, feel free to reopen.
