### ISSUE TITLE
nova 2.10.1 tab fields not showing

### ISSUE THREAD

**Issue by madube** [eminiarts/nova-tabs#90]
try with 
Laravel 6.16.0
Laravel/nova 2.10.1
nova-tabs 1.2.2

the .tab-content in nova-add.css has 
.tab-content {
  max-height: 0;
  display: none;
}

in the detailTabs.vue 
 .tab-content class is set if defaultSearch is false

```
   <div
        :class="[(panel && panel.defaultSearch) ? 'default-search': 'tab-content', slugify(tab.name)]"
        :ref="slugify(tab.name)"
        v-for="(tab, index) in tabs"
        v-show="tab.name == activeTab"
        :label="tab.name"
        :key="'related-tabs-fields' + index"
      >
```

the tabs fields are not showing on page because of the .tab-content atttributs from the nova-add.css.

![Capture](https://user-images.githubusercontent.com/7302459/74768959-7e21d400-5257-11ea-8b24-6afc9ce6cff3.PNG)
![Capture1](https://user-images.githubusercontent.com/7302459/74769039-a14c8380-5257-11ea-9b89-540b621c3add.PNG)

if set true, the default-search class is set instead, now tabs fields are showing ok!  

![Capture2](https://user-images.githubusercontent.com/7302459/74769320-33548c00-5258-11ea-9de8-c7512e68fc2e.PNG)
![Capture3](https://user-images.githubusercontent.com/7302459/74769326-35b6e600-5258-11ea-9bcc-b8ef8f6ac4c3.PNG)

**Comment by RVxLab** [comment]
Sorry for the late response. Is this still an issue at this time?

**Comment by RVxLab** [comment]
Due to the age of this issue I'm closing it. If this is still a problem, feel free to reopen or create a new one. If you do so, please provide information on a more up to date version of Nova.
