### ISSUE TITLE
Support for Laravel 7, Nova 3

### ISSUE THREAD

**Issue by phuclh** [eminiarts/nova-tabs#92]
Will this package support for Laravel 7, Nova 3?

I got this error when using Nova 3.2.1.

`Argument 2 passed to Laravel\Nova\Resource::removeNonCreationFields() must be an instance of Laravel\Nova\Fields\FieldCollection, instance of Illuminate\Support\HigherOrderWhenProxy given, called in /Users/mac/Code/demo/vendor/eminiarts/nova-tabs/src/TabsOnEdit.php on line 22`

**Comment by ziming** [comment]
It works on laravel 7, nova 3 for me.

**Comment by sirikkoster** [comment]
Pullrequest #91 will fix this problem i think

**Comment by ziming** [comment]
I had a PR on laravel/nova that deals with this issue, it was merged some hours ago, download the latest nova from github, it should work now.

**Comment by latwelve** [comment]
Nova 3.2.1 trying to use TabsOnEdit, with no changes from the release package:

`Argument 2 passed to Laravel\Nova\Resource::removeNonCreationFields() must be an instance of Laravel\Nova\Fields\FieldCollection, instance of Illuminate\Support\HigherOrderWhenProxy given, called in /Sites/XXXi/vendor/eminiarts/nova-tabs/src/TabsOnEdit.php on line 22 {"userId":1,"exception":"[object] (TypeError(code: 0): Argument 2 passed to Laravel\\Nova\\Resource::removeNonCreationFields() must be an instance of Laravel\\Nova\\Fields\\FieldCollection, instance of Illuminate\\Support\\HigherOrderWhenProxy given, called in /Sites/XXXi/vendor/eminiarts/nova-tabs/src/TabsOnEdit.php on line 22 at /Sites/XXX/nova/src/ResolvesFields.php:199)`

**Comment by ziming** [comment]
the latest one from github not the latest release on nova website

**Comment by phuclh** [comment]
> the latest one from github not the latest release on nova website

Yes. Thank you!!!
