### ISSUE TITLE
Error in Nova 3 under TabsOnEdit

### ISSUE THREAD

**Issue by ziming** [eminiarts/nova-tabs#93]
Got the following error when I try to edit a resource

Argument 2 passed to Laravel\Nova\Resource::removeNonUpdateFields() must be an instance of Laravel\Nova\Fields\FieldCollection, instance of Illuminate\Support\HigherOrderWhenProxy given, called in ~/laravel-projects/my-project/vendor/eminiarts/nova-tabs/src/TabsOnEdit.php on line 112

Hope it helps. Thanks!

**Comment by krisimmig** [comment]
@ziming I ran into this issue as well, do you know in which verion of nova your PR is included?
