### ISSUE TITLE
doesn't work in nova 3.7.1

### ISSUE THREAD

**Issue by sfgary** [eminiarts/nova-tabs#98]
PHP 7.4
Laravel 7.19.1
Nova 3.7.1

copy the example:
        new Tabs('Tabs', [
            'Balance'    => [
                Number::make('Balance', 'balance'),
                Number::make('Total', 'total'),
            ],
            'Other Info' => [
                Number::make('Paid To Date', 'paid_to_date'),
            ],
        ]),

result:
![image](https://user-images.githubusercontent.com/65210146/87646346-4de84e00-c781-11ea-95c6-3e4ddb079239.png)

**Comment by pleone** [comment]
Same here

**Comment by MilesWuCode** [comment]
same.. nova v3.10.0

**Comment by franraknic** [comment]
Laravel 7.24
Nova 3.8.4

Also not working

**Comment by RVxLab** [comment]
Are you on a form? If so, did you add the `Eminiarts\Tabs\TabsOnEdit` trait?

**Comment by ziming** [comment]
I believe i made a merged PR to nova that fixed this in a newer version. Although it broke again in nova 3.12

**Comment by RVxLab** [comment]
Due to the age of this issue I'm closing it. If my above comment did not help, feel free to reopen this issue or create a new one.
